#!/usr/bin/env bash
# test/pf-product-test-plan.sh — TC-001, TC-002, TC-003, TC-013
# (20260806-feat-product-test-plan).
#
# Covers the Phase 4.5 promotion logic that skills/pf-close/SKILL.md documents
# in prose and a real /pf-close run executes: selecting Manual rows out of an
# issue's Status Tracker, normalizing Priority -> Prio, mapping Status, and the
# phase ordering / Phase 8 commit composition that makes the promotion safe.
#
# Phase 4.5 is interpreted by an LLM agent, not run by this script — so every
# case below transcribes the algorithm to bash AND carries its own drift-guard
# step that greps the real skills/pf-close/SKILL.md for the rule it exercises.
# The transcribed helper matching its own copy of the rule proves nothing by
# itself (test_plan.md, Group A); the drift-guard is what keeps this suite
# honest if Phase 4.5 is ever edited without updating it here.
#
# Later tasks of this issue (TC-004..TC-012, TC-015, TC-017..TC-019) extend
# this same file — see the insertion marker above `assert_repo_untouched` near
# the bottom. Read-only w.r.t. the framework tree (S-5): no tracked file is
# modified, no $HOME is touched, no git command writes, no network is used.

# shellcheck source=test/lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/lib.sh"

PF_CLOSE_SKILL="$REPO_ROOT/skills/pf-close/SKILL.md"
TP_MIXED="$REPO_ROOT/test/fixtures/pf-product-test-plan/issue-mixed-types/docs/issues/open/20990101-feat-fixture-mixed/test_plan.md"

# ─── Helpers: transcribed Phase 4.5 algorithm (specs.md "Stage: /pf-close —
# Phase 4.5", skills/pf-close/SKILL.md Phase 4.5) ──────────────────────────

# pf_ptp_parse_rows <test_plan.md file>
#
# Emits one line per Status Tracker data row, fields joined by \037 (ASCII
# Unit Separator, unlikely to appear in table text): TC<US>Test Case<US>Type
# <US>Priority<US>Status. Columns are resolved BY HEADER NAME, never by fixed
# position — the fixture uses the column order `TC | Test Case | Type |
# Priority | Status | Remarks`, the one real order (also generated by
# ~/.claude/skills/pf-test-plan/SKILL.md Step 4) that a positional parser gets
# wrong: reading the second column as `Type` on this order reads a case title
# instead and selects zero Manual rows.
pf_ptp_parse_rows() {
  local file="$1"
  awk -F'|' '
    BEGIN { intable = 0; header_done = 0; sep_done = 0 }
    /^## Status Tracker/ { intable = 1; next }
    intable && /^##/ { exit }
    !intable { next }
    /^\|/ {
      if (!header_done) {
        for (i = 1; i <= NF; i++) {
          h = $i
          gsub(/^[ \t]+|[ \t]+$/, "", h)
          if (h == "TC") idx_tc = i
          else if (h == "Test Case") idx_case = i
          else if (h == "Type") idx_type = i
          else if (h == "Priority") idx_prio = i
          else if (h == "Status") idx_status = i
        }
        header_done = 1
        next
      }
      if (!sep_done) { sep_done = 1; next }
      tc = $idx_tc; tcase = $idx_case; type = $idx_type; prio = $idx_prio; status = $idx_status
      gsub(/^[ \t]+|[ \t]+$/, "", tc)
      gsub(/^[ \t]+|[ \t]+$/, "", tcase)
      gsub(/^[ \t]+|[ \t]+$/, "", type)
      gsub(/^[ \t]+|[ \t]+$/, "", prio)
      gsub(/^[ \t]+|[ \t]+$/, "", status)
      if (tc == "") next
      printf "%s\037%s\037%s\037%s\037%s\n", tc, tcase, type, prio, status
    }
  ' "$file"
}

# pf_ptp_select_manual <file> — Phase 4.5 step 1: only Type: Manual rows.
# Type: Auto rows (and every one of their fields) are dropped entirely.
pf_ptp_select_manual() {
  local file="$1"
  pf_ptp_parse_rows "$file" | awk -F'\037' '$3 == "Manual"'
}

# pf_ptp_field_for_tc <file> <TC-NNN> <field index 1..5> — one field of one
# parsed row (1=TC 2=Test Case 3=Type 4=Priority 5=Status), used to pull real
# fixture values into TC-002/TC-003 instead of hardcoding them a second time.
pf_ptp_field_for_tc() {
  local file="$1" tc_id="$2" field_index="$3"
  pf_ptp_parse_rows "$file" | awk -F'\037' -v tc="$tc_id" -v fi="$field_index" '$1 == tc { print $fi }'
}

# pf_ptp_normalize_priority <raw Priority> — Phase 4.5 step 3, "Priority
# normalization": Critical->Critical, High->High, Medium->Med, Low->Low. Any
# other value normalizes to Med and carries a non-empty note (the original
# value) so an unrecognized priority doesn't silently vanish. Prints
# "Prio\037note" (note empty for dictionary hits).
pf_ptp_normalize_priority() {
  local raw="$1"
  case "$raw" in
    Critical) printf 'Critical\037' ;;
    High) printf 'High\037' ;;
    Medium) printf 'Med\037' ;;
    Low) printf 'Low\037' ;;
    *) printf 'Med\037original value: %s' "$raw" ;;
  esac
}

# pf_ptp_map_status <raw Status> — Phase 4.5 step 3 field-mapping table:
# [ ] -> pending, ✓ -> ✓, ✗ -> ✗.
pf_ptp_map_status() {
  case "$1" in
    "[ ]") printf 'pending' ;;
    "✓") printf '✓' ;;
    "✗") printf '✗' ;;
    *) printf '%s' "$1" ;;
  esac
}

# pf_ptp_last_run <mapped Status> <closing date> — Phase 4.5 step 3: "—" for
# pending, the issue's closing date otherwise.
pf_ptp_last_run() {
  local status="$1" closing_date="$2"
  if [ "$status" = "pending" ]; then
    printf '%s' '—'
  else
    printf '%s' "$closing_date"
  fi
}

# pf_ptp_phase45_section — the text of skills/pf-close/SKILL.md from its
# "## Phase 4.5" heading (inclusive) up to (exclusive) the next "## Phase "
# heading. Empty if Phase 4.5 does not exist yet.
pf_ptp_phase45_section() {
  awk '
    started && /^## Phase / { exit }
    /^## Phase 4\.5/ { started = 1 }
    started { print }
  ' "$PF_CLOSE_SKILL"
}

# ══════════════════════════════════════════════════════════════════════════════
printf '=== TC-001: only Type: Manual rows are ever selected for promotion (BR-1)\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-001: fixture test_plan.md not found: $TP_MIXED"
else
  selected="$(pf_ptp_select_manual "$TP_MIXED")"

  # Ground truth for step 2, computed independently of pf_ptp_select_manual /
  # pf_ptp_parse_rows by grepping the raw table for the literal Type cell — not
  # by re-running the helper under test, which would just compare it to itself.
  n_manual_raw="$(grep -cE '\| *Manual *\|' "$TP_MIXED")"
  n_auto_raw="$(grep -cE '\| *Auto *\|' "$TP_MIXED")"

  n_selected="$(printf '%s\n' "$selected" | grep -c . || true)"
  n_selected_auto="$(printf '%s\n' "$selected" | awk -F'\037' '$3 == "Auto"' | grep -c . || true)"

  if [ "$n_auto_raw" -ge 1 ] && [ "$n_manual_raw" -ge 2 ] && [ "$n_selected_auto" -eq 0 ]; then
    pf_pass "TC-001 step 1: selection contains no Type: Auto row ($n_auto_raw Auto row(s) in fixture, correctly excluded)"
  else
    pf_fail "TC-001 step 1: an Auto row leaked into the selection, or fixture preconditions unmet (auto_raw=$n_auto_raw manual_raw=$n_manual_raw selected_auto=$n_selected_auto)"
  fi

  if [ "$n_selected" -eq "$n_manual_raw" ]; then
    pf_pass "TC-001 step 2: selected row count ($n_selected) equals the fixture's Type: Manual row count ($n_manual_raw)"
  else
    pf_fail "TC-001 step 2: selection returned $n_selected rows, fixture has $n_manual_raw Type: Manual rows"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_manual_rule=0
  has_auto_excluded=0
  printf '%s\n' "$sec45" | grep -qiE 'Type.{0,10}(is|:).{0,10}Manual' && has_manual_rule=1
  printf '%s\n' "$sec45" | grep -qF 'Type: Auto' && has_auto_excluded=1
  if [ "$has_manual_rule" -eq 1 ] && [ "$has_auto_excluded" -eq 1 ]; then
    pf_pass "TC-001 step 3: Phase 4.5 documents selecting Type: Manual rows and excluding Type: Auto rows"
  else
    pf_fail "TC-001 step 3: Phase 4.5 не документирует отбор по Type: Manual (selection rule found: $has_manual_rule, Auto-exclusion found: $has_auto_excluded)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-002: Priority normalization, including Medium -> Med and the off-dictionary fallback\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-002: fixture test_plan.md not found: $TP_MIXED"
else
  prio_critical="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-002" 4)"
  prio_high="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-003" 4)"
  prio_medium="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-004" 4)"
  prio_low="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-005" 4)"
  prio_offdict="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-006" 4)"

  out_critical="$(pf_ptp_normalize_priority "$prio_critical")"
  out_high="$(pf_ptp_normalize_priority "$prio_high")"
  out_medium="$(pf_ptp_normalize_priority "$prio_medium")"
  out_low="$(pf_ptp_normalize_priority "$prio_low")"

  ok_std=1
  [ "${out_critical%%$'\037'*}" = "Critical" ] || ok_std=0
  [ "${out_high%%$'\037'*}" = "High" ] || ok_std=0
  [ "${out_medium%%$'\037'*}" = "Med" ] || ok_std=0
  [ "${out_low%%$'\037'*}" = "Low" ] || ok_std=0

  if [ "$ok_std" -eq 1 ]; then
    pf_pass "TC-002 step 1: Critical/High/Medium/Low normalize to Critical/High/Med/Low"
  else
    pf_fail "TC-002 step 1: normalization mismatch (Critical->${out_critical%%$'\037'*}, High->${out_high%%$'\037'*}, Medium->${out_medium%%$'\037'*}, Low->${out_low%%$'\037'*})"
  fi

  out_offdict="$(pf_ptp_normalize_priority "$prio_offdict")"
  offdict_prio="${out_offdict%%$'\037'*}"
  offdict_note="${out_offdict#*$'\037'}"
  if [ "$offdict_prio" = "Med" ] && [ -n "$offdict_note" ]; then
    pf_pass "TC-002 step 2: off-dictionary value '$prio_offdict' carries through as Med, noted ($offdict_note)"
  else
    pf_fail "TC-002 step 2: off-dictionary value '$prio_offdict' -> prio='$offdict_prio' note='$offdict_note' (want Med + non-empty note)"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_medium_med=0
  has_offdict_rule=0
  printf '%s\n' "$sec45" | grep -qiE 'Medium.{0,10}(→|->).{0,10}Med' && has_medium_med=1
  printf '%s\n' "$sec45" | grep -qiE 'outside.{0,20}dictionary.{0,40}Med' && has_offdict_rule=1
  if [ "$has_medium_med" -eq 1 ] && [ "$has_offdict_rule" -eq 1 ]; then
    pf_pass "TC-002 step 3: Phase 4.5 documents Medium -> Med and the off-dictionary fallback"
  else
    pf_fail "TC-002 step 3: Phase 4.5 не документирует нормализацию Priority → Prio (Medium->Med found: $has_medium_med, off-dictionary rule found: $has_offdict_rule)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-003: Status mapping [ ] -> pending, ✓ -> ✓, ✗ -> ✗\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-003: fixture test_plan.md not found: $TP_MIXED"
else
  status_pending_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-002" 5)"
  status_pass_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-003" 5)"
  status_fail_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-004" 5)"

  mapped_pending="$(pf_ptp_map_status "$status_pending_raw")"
  mapped_pass="$(pf_ptp_map_status "$status_pass_raw")"
  mapped_fail="$(pf_ptp_map_status "$status_fail_raw")"

  if [ "$mapped_pending" = "pending" ]; then
    pf_pass "TC-003 step 1: '$status_pending_raw' maps to pending"
  else
    pf_fail "TC-003 step 1: '$status_pending_raw' mapped to '$mapped_pending' (want pending)"
  fi
  if [ "$mapped_pass" = "✓" ]; then
    pf_pass "TC-003 step 2: '$status_pass_raw' maps to ✓"
  else
    pf_fail "TC-003 step 2: '$status_pass_raw' mapped to '$mapped_pass' (want ✓)"
  fi
  if [ "$mapped_fail" = "✗" ]; then
    pf_pass "TC-003 step 3: '$status_fail_raw' maps to ✗"
  else
    pf_fail "TC-003 step 3: '$status_fail_raw' mapped to '$mapped_fail' (want ✗)"
  fi

  CLOSING_DATE="2026-08-11"
  lr_pending="$(pf_ptp_last_run "$mapped_pending" "$CLOSING_DATE")"
  lr_pass="$(pf_ptp_last_run "$mapped_pass" "$CLOSING_DATE")"
  lr_fail="$(pf_ptp_last_run "$mapped_fail" "$CLOSING_DATE")"
  if [ "$lr_pending" = "—" ] && [ "$lr_pass" = "$CLOSING_DATE" ] && [ "$lr_fail" = "$CLOSING_DATE" ]; then
    pf_pass "TC-003 step 4: Last run is — for pending and the closing date for ✓/✗"
  else
    pf_fail "TC-003 step 4: Last run mismatch (pending='$lr_pending' want '—'; pass='$lr_pass' fail='$lr_fail' want '$CLOSING_DATE')"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_status_table=0
  has_source_form=0
  has_target_form=0
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF '`[ ]` / `✓` / `✗`' && has_source_form=1
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF '`pending` / `✓` / `✗`' && has_target_form=1
  if [ "$has_source_form" -eq 1 ] && [ "$has_target_form" -eq 1 ]; then
    has_status_table=1
  fi
  has_lastrun_rule=0
  printf '%s\n' "$sec45" | grep -qiE 'Last run.{0,20}—.{0,20}pending' && has_lastrun_rule=1
  if [ "$has_status_table" -eq 1 ] && [ "$has_lastrun_rule" -eq 1 ]; then
    pf_pass "TC-003 step 5: Phase 4.5 documents the [ ]/✓/✗ -> pending/✓/✗ mapping and the Last run rule"
  else
    pf_fail "TC-003 step 5: Phase 4.5 не документирует отображение статусов (status table found: $has_status_table, Last run rule found: $has_lastrun_rule)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-013: /pf-close phase order and Phase 8 archive-commit composition\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$PF_CLOSE_SKILL" ]; then
  pf_fail "TC-013: skills/pf-close/SKILL.md does not exist"
else
  line_phase4="$(grep -n '^## Phase 4: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase45="$(grep -n '^## Phase 4\.5$' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase5="$(grep -n '^## Phase 5: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

  if [ -n "$line_phase4" ] && [ -n "$line_phase45" ] && [ -n "$line_phase5" ] &&
    [ "$line_phase4" -lt "$line_phase45" ] && [ "$line_phase45" -lt "$line_phase5" ]; then
    pf_pass "TC-013 step 1: ## Phase 4 (line $line_phase4) < ## Phase 4.5 (line $line_phase45) < ## Phase 5 (line $line_phase5)"
  else
    pf_fail "TC-013 step 1: Phase 4/4.5/5 headings missing or out of order (Phase4=${line_phase4:-<missing>} Phase4.5=${line_phase45:-<missing>} Phase5=${line_phase5:-<missing>})"
  fi

  line_phase8="$(grep -n '^## Phase 8: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase85="$(grep -n '^## Phase 8\.5: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

  if [ -z "$line_phase8" ]; then
    pf_fail "TC-013 step 2: ## Phase 8: heading not found"
  else
    if [ -n "$line_phase85" ]; then
      phase8_section="$(sed -n "${line_phase8},$((line_phase85 - 1))p" "$PF_CLOSE_SKILL")"
    else
      phase8_section="$(sed -n "${line_phase8},\$p" "$PF_CLOSE_SKILL")"
    fi
    if printf '%s\n' "$phase8_section" | grep -qF 'git add' &&
      printf '%s\n' "$phase8_section" | grep -qF 'docs/planning/test-plan.md'; then
      pf_pass "TC-013 step 2: Phase 8's git add includes docs/planning/test-plan.md"
    else
      pf_fail "TC-013 step 2: Phase 8's git add line does not include docs/planning/test-plan.md"
    fi
  fi
fi

# ─── Insertion point ────────────────────────────────────────────────────────
# Tasks 3-7 of this issue (TC-004..TC-012, TC-015, TC-017..TC-019) each add
# their own "=== TC-NNN: ... ===" section HERE — ABOVE assert_repo_untouched /
# pf_summary below, never below them. pf_summary only tallies PASS/FAIL calls
# made before it runs; appending a new TC section after it would make that
# section's results invisible to the suite's exit code.

assert_repo_untouched
pf_summary
