#!/usr/bin/env bash
# test/pf-product-test-plan.sh — TC-001, TC-002, TC-003, TC-013
# (20260806-feat-product-test-plan).
#
# Covers the Phase 4.5 promotion logic that skills/pf-close/SKILL.md documents
# in prose and a real /pf-close run executes: selecting Manual rows out of an
# issue's Status Tracker, normalizing Priority -> Prio, mapping Status, and the
# phase ordering / Phase 8 commit composition that makes the promotion safe.
#
# Phase 4.5 is interpreted by an LLM agent, not run by this script — so every
# case below transcribes the algorithm to bash AND carries its own drift-guard
# step that greps the real skills/pf-close/SKILL.md for the rule it exercises.
# The transcribed helper matching its own copy of the rule proves nothing by
# itself (test_plan.md, Group A); the drift-guard is what keeps this suite
# honest if Phase 4.5 is ever edited without updating it here.
#
# Later tasks of this issue (TC-004..TC-012, TC-015, TC-017..TC-019) extend
# this same file — see the insertion marker above `assert_repo_untouched` near
# the bottom. Read-only w.r.t. the framework tree (S-5): no tracked file is
# modified, no $HOME is touched, no git command writes, no network is used.

# shellcheck source=test/lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/lib.sh"

PF_CLOSE_SKILL="$REPO_ROOT/skills/pf-close/SKILL.md"
TP_MIXED="$REPO_ROOT/test/fixtures/pf-product-test-plan/issue-mixed-types/docs/issues/open/20990101-feat-fixture-mixed/test_plan.md"

# TC-004/005/006 fixtures (docs/planning/test-plan.md itself, not an issue's
# test_plan.md). Each lives at test/fixtures/pf-product-test-plan/<name>/docs/
# planning/test-plan.md — a nested relative path that pf_setup_case cannot
# take directly (its `cp -a "$src" "$parent/$fixture"` needs the intermediate
# directory of the destination to already exist, which it does not for a
# fixture name containing a slash — confirmed by running it against
# "pf-product-test-plan/global-fresh": `cp: cannot create directory
# '.../pf-product-test-plan/global-fresh': No such file or directory`).
# pf_ptp_case_file below copies just the one file these three cases need into
# a fresh pf_mktemp_d dir instead, keeping the fixture itself read-only (S-3)
# and the temp dir registered for cleanup (S-4).
PTP_FIX_FRESH="global-fresh"
PTP_FIX_RETIRED_DELETED="global-after-retired-deleted"
PTP_FIX_STALE_COUNTER="global-stale-counter"

# pf_ptp_case_file <fixture name under test/fixtures/pf-product-test-plan/>
#
# Copies that fixture's docs/planning/test-plan.md into a fresh temp dir
# (pf_mktemp_d — S-4: registered, cleaned on exit) and prints the path to the
# writable copy. The source fixture under test/fixtures/ is only ever read.
pf_ptp_case_file() {
  local fixture="$1" src work
  src="$PF_FIXTURES_DIR/pf-product-test-plan/$fixture/docs/planning/test-plan.md"
  if [ ! -f "$src" ]; then
    printf ''
    return 1
  fi
  work="$(pf_mktemp_d)" || exit 1
  mkdir -p "$work/docs/planning"
  cp "$src" "$work/docs/planning/test-plan.md"
  printf '%s' "$work/docs/planning/test-plan.md"
}

# ─── Helpers: transcribed Phase 4.5 algorithm (specs.md "Stage: /pf-close —
# Phase 4.5", skills/pf-close/SKILL.md Phase 4.5) ──────────────────────────

# pf_ptp_parse_rows <test_plan.md file>
#
# Emits one line per Status Tracker data row, fields joined by \037 (ASCII
# Unit Separator, unlikely to appear in table text): TC<US>Test Case<US>Type
# <US>Priority<US>Status. Columns are resolved BY HEADER NAME, never by fixed
# position — the fixture uses the column order `TC | Test Case | Type |
# Priority | Status | Remarks`, the one real order (also generated by
# ~/.claude/skills/pf-test-plan/SKILL.md Step 4) that a positional parser gets
# wrong: reading the second column as `Type` on this order reads a case title
# instead and selects zero Manual rows.
pf_ptp_parse_rows() {
  local file="$1"
  awk -F'|' '
    BEGIN { intable = 0; header_done = 0; sep_done = 0 }
    /^## Status Tracker/ { intable = 1; next }
    intable && /^##/ { exit }
    !intable { next }
    /^\|/ {
      if (!header_done) {
        for (i = 1; i <= NF; i++) {
          h = $i
          gsub(/^[ \t]+|[ \t]+$/, "", h)
          if (h == "TC") idx_tc = i
          else if (h == "Test Case") idx_case = i
          else if (h == "Type") idx_type = i
          else if (h == "Priority") idx_prio = i
          else if (h == "Status") idx_status = i
        }
        header_done = 1
        next
      }
      if (!sep_done) { sep_done = 1; next }
      tc = $idx_tc; tcase = $idx_case; type = $idx_type; prio = $idx_prio; status = $idx_status
      gsub(/^[ \t]+|[ \t]+$/, "", tc)
      gsub(/^[ \t]+|[ \t]+$/, "", tcase)
      gsub(/^[ \t]+|[ \t]+$/, "", type)
      gsub(/^[ \t]+|[ \t]+$/, "", prio)
      gsub(/^[ \t]+|[ \t]+$/, "", status)
      if (tc == "") next
      printf "%s\037%s\037%s\037%s\037%s\n", tc, tcase, type, prio, status
    }
  ' "$file"
}

# pf_ptp_select_manual <file> — Phase 4.5 step 1: only Type: Manual rows.
# Type: Auto rows (and every one of their fields) are dropped entirely.
pf_ptp_select_manual() {
  local file="$1"
  pf_ptp_parse_rows "$file" | awk -F'\037' '$3 == "Manual"'
}

# pf_ptp_field_for_tc <file> <TC-NNN> <field index 1..5> — one field of one
# parsed row (1=TC 2=Test Case 3=Type 4=Priority 5=Status), used to pull real
# fixture values into TC-002/TC-003 instead of hardcoding them a second time.
pf_ptp_field_for_tc() {
  local file="$1" tc_id="$2" field_index="$3"
  pf_ptp_parse_rows "$file" | awk -F'\037' -v tc="$tc_id" -v fi="$field_index" '$1 == tc { print $fi }'
}

# pf_ptp_normalize_priority <raw Priority> — Phase 4.5 step 3, "Priority
# normalization": Critical->Critical, High->High, Medium->Med, Low->Low. Any
# other value normalizes to Med and carries a non-empty note (the original
# value) so an unrecognized priority doesn't silently vanish. Prints
# "Prio\037note" (note empty for dictionary hits).
pf_ptp_normalize_priority() {
  local raw="$1"
  case "$raw" in
    Critical) printf 'Critical\037' ;;
    High) printf 'High\037' ;;
    Medium) printf 'Med\037' ;;
    Low) printf 'Low\037' ;;
    *) printf 'Med\037original value: %s' "$raw" ;;
  esac
}

# pf_ptp_map_status <raw Status> — Phase 4.5 step 3 field-mapping table:
# [ ] -> pending, ✓ -> ✓, ✗ -> ✗.
pf_ptp_map_status() {
  case "$1" in
    "[ ]") printf 'pending' ;;
    "✓") printf '✓' ;;
    "✗") printf '✗' ;;
    *) printf '%s' "$1" ;;
  esac
}

# pf_ptp_last_run <mapped Status> <closing date> — Phase 4.5 step 3: "—" for
# pending, the issue's closing date otherwise.
pf_ptp_last_run() {
  local status="$1" closing_date="$2"
  if [ "$status" = "pending" ]; then
    printf '%s' '—'
  else
    printf '%s' "$closing_date"
  fi
}

# pf_ptp_phase45_section — the text of skills/pf-close/SKILL.md from its
# "## Phase 4.5" heading (inclusive) up to (exclusive) the next "## Phase "
# heading. Empty if Phase 4.5 does not exist yet.
pf_ptp_phase45_section() {
  awk '
    started && /^## Phase / { exit }
    /^## Phase 4\.5/ { started = 1 }
    started { print }
  ' "$PF_CLOSE_SKILL"
}

# ─── Helpers: PTC numbering (specs.md "Выделение номера", TC-004/005/006) ──

# pf_ptp_counter_value <docs/planning/test-plan.md file> — the integer encoded
# in its "Last allocated: PTC-NNNN" line, or 0 for "Last allocated: none" (the
# fresh-template state).
pf_ptp_counter_value() {
  local file="$1" line digits
  line="$(grep -m1 '^Last allocated:' "$file" 2>/dev/null || true)"
  case "$line" in
    *none*) printf '0' ;;
    *PTC-*)
      digits="$(printf '%s' "${line##*PTC-}" | tr -dc '0-9')"
      printf '%s' "$((10#${digits:-0}))"
      ;;
    *) printf '0' ;;
  esac
}

# pf_ptp_parse_global_rows <file> — one line per data row of the global
# test-plan.md table (header resolved by the literal "| PTC |" cell, not by a
# fixed line offset, so a fixture with extra prose above the table still
# parses). Fields joined by \037: PTC, Area, Test case, Prio, Origin, Last
# run, Status.
pf_ptp_parse_global_rows() {
  local file="$1"
  awk -F'|' '
    !header && /^\| *PTC *\|/ { header = 1; next }
    header && !sep && /^\| *-/ { sep = 1; next }
    header && sep && /^\|/ {
      ptc = $2; area = $3; tcase = $4; prio = $5; origin = $6; lastrun = $7; status = $8
      gsub(/^[ \t]+|[ \t]+$/, "", ptc)
      gsub(/^[ \t]+|[ \t]+$/, "", area)
      gsub(/^[ \t]+|[ \t]+$/, "", tcase)
      gsub(/^[ \t]+|[ \t]+$/, "", prio)
      gsub(/^[ \t]+|[ \t]+$/, "", origin)
      gsub(/^[ \t]+|[ \t]+$/, "", lastrun)
      gsub(/^[ \t]+|[ \t]+$/, "", status)
      if (ptc == "") next
      printf "%s\037%s\037%s\037%s\037%s\037%s\037%s\n", ptc, area, tcase, prio, origin, lastrun, status
    }
  ' "$file"
}

# pf_ptp_max_table_number <file> — highest PTC-NNNN numeric value already
# written in the table, or 0 for an empty table.
pf_ptp_max_table_number() {
  local file="$1" max=0 n digits
  while IFS= read -r n; do
    [ -z "$n" ] && continue
    digits="$(printf '%s' "${n#PTC-}" | tr -dc '0-9')"
    n="$((10#${digits:-0}))"
    [ "$n" -gt "$max" ] && max="$n"
  done < <(pf_ptp_parse_global_rows "$file" | awk -F'\037' '{ print $1 }')
  printf '%s' "$max"
}

# pf_ptp_next_number <file> — specs.md "Выделение номера": next PTC number is
# the maximum of (a) the Last allocated: counter and (b) the highest PTC
# already in the table, plus one. Formatted PTC-NNNN (4 digits).
pf_ptp_next_number() {
  local file="$1" counter table_max winner next
  counter="$(pf_ptp_counter_value "$file")"
  table_max="$(pf_ptp_max_table_number "$file")"
  winner="$counter"
  [ "$table_max" -gt "$winner" ] && winner="$table_max"
  next=$((winner + 1))
  printf 'PTC-%04d' "$next"
}

# pf_ptp_promote_row <file> <area> <test case> <prio> <origin> <last run>
# <status> — simulates Phase 4.5 steps 3-4 for exactly one Manual case:
# appends the new row with the number pf_ptp_next_number computes, then
# updates the Last allocated: line to that same number. Mutates <file> (a
# $TMP_WORK copy, never the read-only fixture — S-3). Prints the PTC assigned.
pf_ptp_promote_row() {
  local file="$1" area="$2" tcase="$3" prio="$4" origin="$5" lastrun="$6" status="$7"
  local ptc
  ptc="$(pf_ptp_next_number "$file")"
  printf '| %s | %s | %s | %s | %s | %s | %s |\n' \
    "$ptc" "$area" "$tcase" "$prio" "$origin" "$lastrun" "$status" >>"$file"
  sed -i "s/^Last allocated:.*/Last allocated: $ptc/" "$file"
  printf '%s' "$ptc"
}

# assert_numbering_rule_documented <step label> — shared drift-guard for
# TC-004/005/006 step 3 (test_plan.md: "тот же grep... с тем же сообщением,
# что TC-004 шаг 3" — one function so the wording never drifts between three
# copies). Greps the live Phase 4.5 text for the rule "next number = maximum
# of Last allocated: and the highest table PTC, plus one" (specs.md, Task 1
# pt. 4). The core diagnostic text is identical across all three callers; only
# the "<step label>:" prefix differs, per this suite's TC-ID-first convention.
assert_numbering_rule_documented() {
  local step_label="$1" sec45 has_rule=0
  sec45="$(pf_ptp_phase45_section)"
  if printf '%s\n' "$sec45" |
    grep -qiE 'maximum of.*\(a\).*Last allocated.*\(b\).*highest.*PTC.*table.*plus one'; then
    has_rule=1
  fi
  if [ "$has_rule" -eq 1 ]; then
    pf_pass "$step_label: Phase 4.5 documents the PTC numbering rule (max of Last allocated: and highest table PTC, plus one)"
  else
    pf_fail "$step_label: Phase 4.5 не документирует правило выделения номера"
  fi
}

# ══════════════════════════════════════════════════════════════════════════════
printf '=== TC-001: only Type: Manual rows are ever selected for promotion (BR-1)\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-001: fixture test_plan.md not found: $TP_MIXED"
else
  selected="$(pf_ptp_select_manual "$TP_MIXED")"

  # Ground truth for step 2, computed independently of pf_ptp_select_manual /
  # pf_ptp_parse_rows by grepping the raw table for the literal Type cell — not
  # by re-running the helper under test, which would just compare it to itself.
  n_manual_raw="$(grep -cE '\| *Manual *\|' "$TP_MIXED")"
  n_auto_raw="$(grep -cE '\| *Auto *\|' "$TP_MIXED")"

  n_selected="$(printf '%s\n' "$selected" | grep -c . || true)"
  n_selected_auto="$(printf '%s\n' "$selected" | awk -F'\037' '$3 == "Auto"' | grep -c . || true)"

  if [ "$n_auto_raw" -ge 1 ] && [ "$n_manual_raw" -ge 2 ] && [ "$n_selected_auto" -eq 0 ]; then
    pf_pass "TC-001 step 1: selection contains no Type: Auto row ($n_auto_raw Auto row(s) in fixture, correctly excluded)"
  else
    pf_fail "TC-001 step 1: an Auto row leaked into the selection, or fixture preconditions unmet (auto_raw=$n_auto_raw manual_raw=$n_manual_raw selected_auto=$n_selected_auto)"
  fi

  if [ "$n_selected" -eq "$n_manual_raw" ]; then
    pf_pass "TC-001 step 2: selected row count ($n_selected) equals the fixture's Type: Manual row count ($n_manual_raw)"
  else
    pf_fail "TC-001 step 2: selection returned $n_selected rows, fixture has $n_manual_raw Type: Manual rows"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_manual_rule=0
  has_auto_excluded=0
  printf '%s\n' "$sec45" | grep -qiE 'Type.{0,10}(is|:).{0,10}Manual' && has_manual_rule=1
  printf '%s\n' "$sec45" | grep -qF 'Type: Auto' && has_auto_excluded=1
  if [ "$has_manual_rule" -eq 1 ] && [ "$has_auto_excluded" -eq 1 ]; then
    pf_pass "TC-001 step 3: Phase 4.5 documents selecting Type: Manual rows and excluding Type: Auto rows"
  else
    pf_fail "TC-001 step 3: Phase 4.5 не документирует отбор по Type: Manual (selection rule found: $has_manual_rule, Auto-exclusion found: $has_auto_excluded)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-002: Priority normalization, including Medium -> Med and the off-dictionary fallback\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-002: fixture test_plan.md not found: $TP_MIXED"
else
  prio_critical="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-002" 4)"
  prio_high="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-003" 4)"
  prio_medium="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-004" 4)"
  prio_low="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-005" 4)"
  prio_offdict="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-006" 4)"

  out_critical="$(pf_ptp_normalize_priority "$prio_critical")"
  out_high="$(pf_ptp_normalize_priority "$prio_high")"
  out_medium="$(pf_ptp_normalize_priority "$prio_medium")"
  out_low="$(pf_ptp_normalize_priority "$prio_low")"

  ok_std=1
  [ "${out_critical%%$'\037'*}" = "Critical" ] || ok_std=0
  [ "${out_high%%$'\037'*}" = "High" ] || ok_std=0
  [ "${out_medium%%$'\037'*}" = "Med" ] || ok_std=0
  [ "${out_low%%$'\037'*}" = "Low" ] || ok_std=0

  if [ "$ok_std" -eq 1 ]; then
    pf_pass "TC-002 step 1: Critical/High/Medium/Low normalize to Critical/High/Med/Low"
  else
    pf_fail "TC-002 step 1: normalization mismatch (Critical->${out_critical%%$'\037'*}, High->${out_high%%$'\037'*}, Medium->${out_medium%%$'\037'*}, Low->${out_low%%$'\037'*})"
  fi

  out_offdict="$(pf_ptp_normalize_priority "$prio_offdict")"
  offdict_prio="${out_offdict%%$'\037'*}"
  offdict_note="${out_offdict#*$'\037'}"
  if [ "$offdict_prio" = "Med" ] && [ -n "$offdict_note" ]; then
    pf_pass "TC-002 step 2: off-dictionary value '$prio_offdict' carries through as Med, noted ($offdict_note)"
  else
    pf_fail "TC-002 step 2: off-dictionary value '$prio_offdict' -> prio='$offdict_prio' note='$offdict_note' (want Med + non-empty note)"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_medium_med=0
  has_offdict_rule=0
  printf '%s\n' "$sec45" | grep -qiE 'Medium.{0,10}(→|->).{0,10}Med' && has_medium_med=1
  printf '%s\n' "$sec45" | grep -qiE 'outside.{0,20}dictionary.{0,40}Med' && has_offdict_rule=1
  if [ "$has_medium_med" -eq 1 ] && [ "$has_offdict_rule" -eq 1 ]; then
    pf_pass "TC-002 step 3: Phase 4.5 documents Medium -> Med and the off-dictionary fallback"
  else
    pf_fail "TC-002 step 3: Phase 4.5 не документирует нормализацию Priority → Prio (Medium->Med found: $has_medium_med, off-dictionary rule found: $has_offdict_rule)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-003: Status mapping [ ] -> pending, ✓ -> ✓, ✗ -> ✗\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-003: fixture test_plan.md not found: $TP_MIXED"
else
  status_pending_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-002" 5)"
  status_pass_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-003" 5)"
  status_fail_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-004" 5)"

  mapped_pending="$(pf_ptp_map_status "$status_pending_raw")"
  mapped_pass="$(pf_ptp_map_status "$status_pass_raw")"
  mapped_fail="$(pf_ptp_map_status "$status_fail_raw")"

  if [ "$mapped_pending" = "pending" ]; then
    pf_pass "TC-003 step 1: '$status_pending_raw' maps to pending"
  else
    pf_fail "TC-003 step 1: '$status_pending_raw' mapped to '$mapped_pending' (want pending)"
  fi
  if [ "$mapped_pass" = "✓" ]; then
    pf_pass "TC-003 step 2: '$status_pass_raw' maps to ✓"
  else
    pf_fail "TC-003 step 2: '$status_pass_raw' mapped to '$mapped_pass' (want ✓)"
  fi
  if [ "$mapped_fail" = "✗" ]; then
    pf_pass "TC-003 step 3: '$status_fail_raw' maps to ✗"
  else
    pf_fail "TC-003 step 3: '$status_fail_raw' mapped to '$mapped_fail' (want ✗)"
  fi

  CLOSING_DATE="2026-08-11"
  lr_pending="$(pf_ptp_last_run "$mapped_pending" "$CLOSING_DATE")"
  lr_pass="$(pf_ptp_last_run "$mapped_pass" "$CLOSING_DATE")"
  lr_fail="$(pf_ptp_last_run "$mapped_fail" "$CLOSING_DATE")"
  if [ "$lr_pending" = "—" ] && [ "$lr_pass" = "$CLOSING_DATE" ] && [ "$lr_fail" = "$CLOSING_DATE" ]; then
    pf_pass "TC-003 step 4: Last run is — for pending and the closing date for ✓/✗"
  else
    pf_fail "TC-003 step 4: Last run mismatch (pending='$lr_pending' want '—'; pass='$lr_pass' fail='$lr_fail' want '$CLOSING_DATE')"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_status_table=0
  has_source_form=0
  has_target_form=0
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF '`[ ]` / `✓` / `✗`' && has_source_form=1
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF '`pending` / `✓` / `✗`' && has_target_form=1
  if [ "$has_source_form" -eq 1 ] && [ "$has_target_form" -eq 1 ]; then
    has_status_table=1
  fi
  has_lastrun_rule=0
  printf '%s\n' "$sec45" | grep -qiE 'Last run.{0,20}—.{0,20}pending' && has_lastrun_rule=1
  if [ "$has_status_table" -eq 1 ] && [ "$has_lastrun_rule" -eq 1 ]; then
    pf_pass "TC-003 step 5: Phase 4.5 documents the [ ]/✓/✗ -> pending/✓/✗ mapping and the Last run rule"
  else
    pf_fail "TC-003 step 5: Phase 4.5 не документирует отображение статусов (status table found: $has_status_table, Last run rule found: $has_lastrun_rule)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-013: /pf-close phase order and Phase 8 archive-commit composition\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$PF_CLOSE_SKILL" ]; then
  pf_fail "TC-013: skills/pf-close/SKILL.md does not exist"
else
  line_phase4="$(grep -n '^## Phase 4: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase45="$(grep -n '^## Phase 4\.5$' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase5="$(grep -n '^## Phase 5: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

  if [ -n "$line_phase4" ] && [ -n "$line_phase45" ] && [ -n "$line_phase5" ] &&
    [ "$line_phase4" -lt "$line_phase45" ] && [ "$line_phase45" -lt "$line_phase5" ]; then
    pf_pass "TC-013 step 1: ## Phase 4 (line $line_phase4) < ## Phase 4.5 (line $line_phase45) < ## Phase 5 (line $line_phase5)"
  else
    pf_fail "TC-013 step 1: Phase 4/4.5/5 headings missing or out of order (Phase4=${line_phase4:-<missing>} Phase4.5=${line_phase45:-<missing>} Phase5=${line_phase5:-<missing>})"
  fi

  line_phase8="$(grep -n '^## Phase 8: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase85="$(grep -n '^## Phase 8\.5: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

  if [ -z "$line_phase8" ]; then
    pf_fail "TC-013 step 2: ## Phase 8: heading not found"
  else
    if [ -n "$line_phase85" ]; then
      phase8_section="$(sed -n "${line_phase8},$((line_phase85 - 1))p" "$PF_CLOSE_SKILL")"
    else
      phase8_section="$(sed -n "${line_phase8},\$p" "$PF_CLOSE_SKILL")"
    fi
    if printf '%s\n' "$phase8_section" | grep -qF 'git add' &&
      printf '%s\n' "$phase8_section" | grep -qF 'docs/planning/test-plan.md'; then
      pf_pass "TC-013 step 2: Phase 8's git add includes docs/planning/test-plan.md"
    else
      pf_fail "TC-013 step 2: Phase 8's git add line does not include docs/planning/test-plan.md"
    fi
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-004: PTC numbering on a fresh/empty docs/planning/test-plan.md\n'
# ══════════════════════════════════════════════════════════════════════════════

tp004="$(pf_ptp_case_file "$PTP_FIX_FRESH")"

if [ ! -f "$tp004" ]; then
  pf_fail "TC-004: fixture docs/planning/test-plan.md not found ($PTP_FIX_FRESH)"
else
  next004="$(pf_ptp_next_number "$tp004")"
  if [ "$next004" = "PTC-0001" ]; then
    pf_pass "TC-004 step 1: numbering on an empty table yields PTC-0001"
  else
    pf_fail "TC-004 step 1: numbering on an empty table yielded $next004, want PTC-0001"
  fi

  assigned004="$(pf_ptp_promote_row "$tp004" "explorer-ui" \
    "Тема сохраняется между перезагрузками страницы" "High" \
    "20990101-feat-fixture-mixed#TC-005" "—" "pending")"
  last_alloc004="$(pf_ptp_counter_value "$tp004")"
  row_count004="$(pf_ptp_parse_global_rows "$tp004" | grep -c . || true)"

  if [ "$assigned004" = "PTC-0001" ] && [ "$last_alloc004" -eq 1 ] && [ "$row_count004" -eq 1 ]; then
    pf_pass "TC-004 step 2: promoting one Manual case onto the fresh file gets PTC-0001 and Last allocated: is updated to it"
  else
    pf_fail "TC-004 step 2: promotion assigned '$assigned004' (want PTC-0001), Last allocated: now $last_alloc004, row count $row_count004"
  fi
fi

assert_numbering_rule_documented "TC-004 step 3"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-005: PTC numbering after a retired row was deleted by hand (counter wins)\n'
# ══════════════════════════════════════════════════════════════════════════════

tp005="$(pf_ptp_case_file "$PTP_FIX_RETIRED_DELETED")"

if [ ! -f "$tp005" ]; then
  pf_fail "TC-005: fixture docs/planning/test-plan.md not found ($PTP_FIX_RETIRED_DELETED)"
else
  counter005="$(pf_ptp_counter_value "$tp005")"
  table_max005="$(pf_ptp_max_table_number "$tp005")"
  next005="$(pf_ptp_next_number "$tp005")"

  if [ "$counter005" -eq 7 ] && [ "$table_max005" -eq 5 ] && [ "$next005" = "PTC-0008" ]; then
    pf_pass "TC-005 step 1: max(Last allocated: PTC-0007, table max PTC-0005) + 1 = PTC-0008, not PTC-0006"
  else
    pf_fail "TC-005 step 1: counter=$counter005 table_max=$table_max005 next=$next005 (want counter=7 table_max=5 next=PTC-0008)"
  fi

  assigned005="$(pf_ptp_promote_row "$tp005" "pf-close" \
    "Восстановление после сбоя в середине Phase 4.5" "Critical" \
    "20990101-feat-fixture-mixed#TC-006" "—" "pending")"
  n_0006="$(grep -c 'PTC-0006' "$tp005" || true)"
  n_0007="$(grep -c 'PTC-0007' "$tp005" || true)"

  if [ "$assigned005" = "PTC-0008" ] && [ "$n_0006" -eq 0 ] && [ "$n_0007" -eq 0 ]; then
    pf_pass "TC-005 step 2: new row got PTC-0008; PTC-0006/PTC-0007 (deleted retired rows) do not reappear"
  else
    pf_fail "TC-005 step 2: new row got '$assigned005' (want PTC-0008); PTC-0006 occurrences=$n_0006 PTC-0007 occurrences=$n_0007 (want 0/0)"
  fi
fi

assert_numbering_rule_documented "TC-005 step 3"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-006: PTC numbering with a stale counter behind written rows (table wins)\n'
# ══════════════════════════════════════════════════════════════════════════════

tp006="$(pf_ptp_case_file "$PTP_FIX_STALE_COUNTER")"

if [ ! -f "$tp006" ]; then
  pf_fail "TC-006: fixture docs/planning/test-plan.md not found ($PTP_FIX_STALE_COUNTER)"
else
  counter006="$(pf_ptp_counter_value "$tp006")"
  table_max006="$(pf_ptp_max_table_number "$tp006")"
  next006="$(pf_ptp_next_number "$tp006")"

  if [ "$counter006" -eq 3 ] && [ "$table_max006" -eq 5 ] && [ "$next006" = "PTC-0006" ]; then
    pf_pass "TC-006 step 1: max(Last allocated: PTC-0003, table max PTC-0005) + 1 = PTC-0006, not PTC-0004"
  else
    pf_fail "TC-006 step 1: counter=$counter006 table_max=$table_max006 next=$next006 (want counter=3 table_max=5 next=PTC-0006)"
  fi

  assigned006="$(pf_ptp_promote_row "$tp006" "scripts" \
    "Идемпотентность повторного запуска Phase 4.5 при одинаковых названиях" "High" \
    "20990101-feat-fixture-mixed#TC-007" "—" "pending")"
  last_alloc006="$(pf_ptp_counter_value "$tp006")"

  if [ "$assigned006" = "PTC-0006" ] && [ "$last_alloc006" -eq 6 ]; then
    pf_pass "TC-006 step 2: new row got PTC-0006 (not a re-issue of an existing row's number) and Last allocated: is updated to it"
  else
    pf_fail "TC-006 step 2: new row got '$assigned006' (want PTC-0006), Last allocated: now $last_alloc006 (want 6)"
  fi
fi

assert_numbering_rule_documented "TC-006 step 3"

# ─── Insertion point ────────────────────────────────────────────────────────
# Tasks 4-7 of this issue (TC-007..TC-012, TC-015, TC-017..TC-019) each add
# their own "=== TC-NNN: ... ===" section HERE — ABOVE assert_repo_untouched /
# pf_summary below, never below them. pf_summary only tallies PASS/FAIL calls
# made before it runs; appending a new TC section after it would make that
# section's results invisible to the suite's exit code.

# ─── pf_validate_test_plan_file: shared row-shape validator (Task 4) ───────
# Defined here, ABOVE its first call (TC-007 below), on purpose: Task 5's
# TC-009 and Task 7's TC-018/TC-019 call this same function later in this
# file, and this suite executes top to bottom in one interpreter pass — the
# definition must physically precede every call site (implementation_plan.md
# Task 4 note on task ordering). Nothing here is a stub; this is the one real
# implementation all four call sites share.

# _pf_ptp_trim <string> — strip leading/trailing whitespace from one table
# cell after it has been split out of a row.
_pf_ptp_trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

# pf_validate_test_plan_file <path to a docs/planning/test-plan.md-shaped file>
#
# Read-only structural validator for the global list's format (specs.md "Data
# model", "Устойчивость к ручной правке"). Contract:
#   - Never writes to <path> — TC-019 (Task 7) diffs the file before/after a
#     run to prove this.
#   - Prints one diagnostic line per violation to stdout, each naming the
#     concrete rule broken (a duplicate PTC number and its value, the bad
#     field and the value it held, or the missing counter line) — never a
#     generic "invalid file".
#   - Returns 0 iff zero violations were found (a well-formed file with zero
#     data rows, e.g. the fresh template, is valid). Returns 1 otherwise,
#     including when <path> itself does not exist.
# Checks performed, in specs.md order: (1) a "Last allocated:" counter line
# exists above the table; (2) every data row splits into exactly 7 fields
# (PTC | Area | Test case | Prio | Origin | Last run | Status) once `\|`
# escape sequences are masked out of the split — an escaped pipe inside Area/
# Test case/Origin must never be mistaken for a column boundary; (3) `PTC` is
# exactly `PTC-NNNN` (4 digits); (4) no two rows share the same `PTC` (BR-2's
# uniqueness is DETECTED post-hoc here, deliberately not prevented at write
# time — specs.md: two branches promoting in parallel both write the same
# next number and git merges that silently, so the first `make test` after
# the merge is where this is meant to be caught); (5) `Prio` is one of the
# closed dictionary {Critical, High, Med, Low}; (6) `Status` is one of the
# closed dictionary {pending, ✓, ✗, retired}.
pf_validate_test_plan_file() {
  local file="$1"
  local ok=0
  local seen_ptcs=$'\002'

  if [ ! -f "$file" ]; then
    printf 'file not found: %s\n' "$file"
    return 1
  fi

  if ! grep -q '^Last allocated:' "$file"; then
    printf 'missing "Last allocated:" counter line above the table\n'
    ok=1
  fi

  local header_done=0 sep_done=0 rawline masked needle n_fields
  local ptc prio status
  local -a cells
  while IFS= read -r rawline; do
    if [ "$header_done" -eq 0 ]; then
      if [[ "$rawline" =~ ^\|[[:space:]]*PTC[[:space:]]*\| ]]; then
        header_done=1
      fi
      continue
    fi
    if [ "$sep_done" -eq 0 ]; then
      if [[ "$rawline" =~ ^\|[[:space:]]*-{2,} ]]; then
        sep_done=1
      fi
      continue
    fi
    [[ "$rawline" =~ ^\| ]] || continue

    # Mask \| before splitting on | — an escaped pipe inside a cell (specs.md:
    # "|" in Area/Test case/Origin is written as "\|") is not a column
    # boundary. Unmasking isn't needed below: only PTC/Prio/Status are
    # inspected, and none of those three ever legitimately contains a pipe.
    masked="${rawline//\\|/$'\001'}"
    IFS='|' read -ra cells <<<"$masked"
    n_fields=$(( ${#cells[@]} - 1 )) # cells[0] is the empty slot before the leading "|"
    if [ "$n_fields" -ne 7 ]; then
      printf 'row has %d field(s), expected 7 (PTC | Area | Test case | Prio | Origin | Last run | Status): %s\n' \
        "$n_fields" "$rawline"
      ok=1
      continue
    fi

    ptc="$(_pf_ptp_trim "${cells[1]}")"
    prio="$(_pf_ptp_trim "${cells[4]}")"
    status="$(_pf_ptp_trim "${cells[7]}")"

    if [[ ! "$ptc" =~ ^PTC-[0-9]{4}$ ]]; then
      printf "PTC field '%s' does not match PTC-NNNN (exactly 4 digits): %s\n" "$ptc" "$rawline"
      ok=1
    fi

    needle=$'\002'"$ptc"$'\002'
    case "$seen_ptcs" in
      *"$needle"*)
        printf 'duplicate PTC %s found (row: %s)\n' "$ptc" "$rawline"
        ok=1
        ;;
      *) seen_ptcs="${seen_ptcs}${ptc}"$'\002' ;;
    esac

    case "$prio" in
      Critical | High | Med | Low) : ;;
      *)
        printf "Prio value '%s' outside the closed dictionary (Critical|High|Med|Low): %s\n" "$prio" "$rawline"
        ok=1
        ;;
    esac

    case "$status" in
      pending | "✓" | "✗" | retired) : ;;
      *)
        printf "Status value '%s' outside the closed dictionary (pending|✓|✗|retired): %s\n" "$status" "$rawline"
        ok=1
        ;;
    esac
  done <"$file"

  return "$ok"
}

PTP_SUITE_SELF="$REPO_ROOT/test/pf-product-test-plan.sh"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-007: a duplicate PTC across two rows is detected, not prevented\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$PTP_SUITE_SELF" ]; then
  pf_fail "TC-007 step 1: test/pf-product-test-plan.sh ещё не создан (задача реализации)"
else
  pf_pass "TC-007 step 1: test/pf-product-test-plan.sh существует"

  tp007="$(pf_ptp_case_file "global-duplicate-ptc")"
  if [ ! -f "$tp007" ]; then
    pf_fail "TC-007: fixture docs/planning/test-plan.md not found (global-duplicate-ptc)"
  else
    out007="$(pf_validate_test_plan_file "$tp007" 2>&1)"
    rc007=$?

    if [ "$rc007" -ne 0 ]; then
      pf_pass "TC-007 step 2: validator exits non-zero on a table containing two PTC-0012 rows"
    else
      pf_fail "TC-007 step 2: детектор дублей PTC не реализован — validator exited 0 on a duplicate PTC-0012"
    fi

    if printf '%s\n' "$out007" | grep -qF 'PTC-0012'; then
      pf_pass "TC-007 step 3: validator output names the duplicated number PTC-0012"
    else
      pf_fail "TC-007 step 3: детектор дублей PTC не реализован — output does not name PTC-0012 (got: $out007)"
    fi
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-008: row shape and the closed Prio/Status dictionaries\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$PTP_SUITE_SELF" ]; then
  pf_fail "TC-008 step 1: test/pf-product-test-plan.sh ещё не создан (задача реализации)"
else
  pf_pass "TC-008 step 1: test/pf-product-test-plan.sh существует"

  tp008_prio="$(pf_ptp_case_file "global-malformed-rows/prio-bad")"
  if [ ! -f "$tp008_prio" ]; then
    pf_fail "TC-008 step 2: fixture not found (global-malformed-rows/prio-bad)"
  else
    out="$(pf_validate_test_plan_file "$tp008_prio" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'Prio'; then
      pf_pass "TC-008 step 2: validator rejects 'Prio: Medium' (outside Critical/High/Med/Low), naming the Prio field ($out)"
    else
      pf_fail "TC-008 step 2: валидация Prio не реализована (rc=$rc, output: $out)"
    fi
  fi

  tp008_status="$(pf_ptp_case_file "global-malformed-rows/status-bad")"
  if [ ! -f "$tp008_status" ]; then
    pf_fail "TC-008 step 3: fixture not found (global-malformed-rows/status-bad)"
  else
    out="$(pf_validate_test_plan_file "$tp008_status" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'Status'; then
      pf_pass "TC-008 step 3: validator rejects 'Status: Passed' (a made-up value), naming the Status field ($out)"
    else
      pf_fail "TC-008 step 3: валидация Status не реализована (rc=$rc, output: $out)"
    fi
  fi

  tp008_ptc="$(pf_ptp_case_file "global-malformed-rows/ptc-bad")"
  if [ ! -f "$tp008_ptc" ]; then
    pf_fail "TC-008 step 4: fixture not found (global-malformed-rows/ptc-bad)"
  else
    out="$(pf_validate_test_plan_file "$tp008_ptc" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'PTC-12'; then
      pf_pass "TC-008 step 4: validator rejects the malformed number PTC-12 (not 4 digits), naming the bad form ($out)"
    else
      pf_fail "TC-008 step 4: валидация формы PTC не реализована (rc=$rc, output: $out)"
    fi
  fi

  tp008_nocounter="$(pf_ptp_case_file "global-malformed-rows/no-counter")"
  if [ ! -f "$tp008_nocounter" ]; then
    pf_fail "TC-008 step 5: fixture not found (global-malformed-rows/no-counter)"
  else
    out="$(pf_validate_test_plan_file "$tp008_nocounter" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'Last allocated'; then
      pf_pass "TC-008 step 5: validator rejects a table with no 'Last allocated:' line above it, naming the missing counter ($out)"
    else
      pf_fail "TC-008 step 5: проверка наличия Last allocated: не реализована (rc=$rc, output: $out)"
    fi
  fi
fi

assert_repo_untouched
pf_summary
