#!/usr/bin/env bash
# test/pf-product-test-plan.sh — TC-001, TC-002, TC-003, TC-013
# (20260806-feat-product-test-plan).
#
# Covers the Phase 4.5 promotion logic that skills/pf-close/SKILL.md documents
# in prose and a real /pf-close run executes: selecting Manual rows out of an
# issue's Status Tracker, normalizing Priority -> Prio, mapping Status, and the
# phase ordering / Phase 8 commit composition that makes the promotion safe.
#
# Phase 4.5 is interpreted by an LLM agent, not run by this script — so every
# case below transcribes the algorithm to bash AND carries its own drift-guard
# step that greps the real skills/pf-close/SKILL.md for the rule it exercises.
# The transcribed helper matching its own copy of the rule proves nothing by
# itself (test_plan.md, Group A); the drift-guard is what keeps this suite
# honest if Phase 4.5 is ever edited without updating it here.
#
# Later tasks of this issue (TC-004..TC-012, TC-015, TC-017..TC-019) extend
# this same file — see the insertion marker above `assert_repo_untouched` near
# the bottom. Read-only w.r.t. the framework tree (S-5): no tracked file is
# modified, no $HOME is touched, no git command writes, no network is used.

# shellcheck source=test/lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/lib.sh"

PF_CLOSE_SKILL="$REPO_ROOT/skills/pf-close/SKILL.md"
TP_MIXED="$REPO_ROOT/test/fixtures/pf-product-test-plan/issue-mixed-types/docs/issues/open/20990101-feat-fixture-mixed/test_plan.md"

# TC-004/005/006 fixtures (docs/planning/test-plan.md itself, not an issue's
# test_plan.md). Each lives at test/fixtures/pf-product-test-plan/<name>/docs/
# planning/test-plan.md — a nested relative path that pf_setup_case cannot
# take directly (its `cp -a "$src" "$parent/$fixture"` needs the intermediate
# directory of the destination to already exist, which it does not for a
# fixture name containing a slash — confirmed by running it against
# "pf-product-test-plan/global-fresh": `cp: cannot create directory
# '.../pf-product-test-plan/global-fresh': No such file or directory`).
# pf_ptp_case_file below copies just the one file these three cases need into
# a fresh pf_mktemp_d dir instead, keeping the fixture itself read-only (S-3)
# and the temp dir registered for cleanup (S-4).
PTP_FIX_FRESH="global-fresh"
PTP_FIX_RETIRED_DELETED="global-after-retired-deleted"
PTP_FIX_STALE_COUNTER="global-stale-counter"

# pf_ptp_case_file <fixture name under test/fixtures/pf-product-test-plan/>
#
# Copies that fixture's docs/planning/test-plan.md into a fresh temp dir
# (pf_mktemp_d — S-4: registered, cleaned on exit) and prints the path to the
# writable copy. The source fixture under test/fixtures/ is only ever read.
pf_ptp_case_file() {
  local fixture="$1" src work
  src="$PF_FIXTURES_DIR/pf-product-test-plan/$fixture/docs/planning/test-plan.md"
  if [ ! -f "$src" ]; then
    printf ''
    return 1
  fi
  work="$(pf_mktemp_d)" || exit 1
  mkdir -p "$work/docs/planning"
  cp "$src" "$work/docs/planning/test-plan.md"
  printf '%s' "$work/docs/planning/test-plan.md"
}

# ─── Helpers: transcribed Phase 4.5 algorithm (specs.md "Stage: /pf-close —
# Phase 4.5", skills/pf-close/SKILL.md Phase 4.5) ──────────────────────────

# pf_ptp_parse_rows <test_plan.md file>
#
# Emits one line per Status Tracker data row, fields joined by \037 (ASCII
# Unit Separator, unlikely to appear in table text): TC<US>Test Case<US>Type
# <US>Priority<US>Status. Columns are resolved BY HEADER NAME, never by fixed
# position — the fixture uses the column order `TC | Test Case | Type |
# Priority | Status | Remarks`, the one real order (also generated by
# ~/.claude/skills/pf-test-plan/SKILL.md Step 4) that a positional parser gets
# wrong: reading the second column as `Type` on this order reads a case title
# instead and selects zero Manual rows.
pf_ptp_parse_rows() {
  local file="$1"
  awk -F'|' '
    BEGIN { intable = 0; header_done = 0; sep_done = 0 }
    /^## Status Tracker/ { intable = 1; next }
    intable && /^##/ { exit }
    !intable { next }
    /^\|/ {
      if (!header_done) {
        for (i = 1; i <= NF; i++) {
          h = $i
          gsub(/^[ \t]+|[ \t]+$/, "", h)
          if (h == "TC") idx_tc = i
          else if (h == "Test Case") idx_case = i
          else if (h == "Type") idx_type = i
          else if (h == "Priority") idx_prio = i
          else if (h == "Status") idx_status = i
        }
        header_done = 1
        next
      }
      if (!sep_done) { sep_done = 1; next }
      tc = $idx_tc; tcase = $idx_case; type = $idx_type; prio = $idx_prio; status = $idx_status
      gsub(/^[ \t]+|[ \t]+$/, "", tc)
      gsub(/^[ \t]+|[ \t]+$/, "", tcase)
      gsub(/^[ \t]+|[ \t]+$/, "", type)
      gsub(/^[ \t]+|[ \t]+$/, "", prio)
      gsub(/^[ \t]+|[ \t]+$/, "", status)
      if (tc == "") next
      printf "%s\037%s\037%s\037%s\037%s\n", tc, tcase, type, prio, status
    }
  ' "$file"
}

# pf_ptp_select_manual <file> — Phase 4.5 step 1: only Type: Manual rows.
# Type: Auto rows (and every one of their fields) are dropped entirely.
pf_ptp_select_manual() {
  local file="$1"
  pf_ptp_parse_rows "$file" | awk -F'\037' '$3 == "Manual"'
}

# pf_ptp_field_for_tc <file> <TC-NNN> <field index 1..5> — one field of one
# parsed row (1=TC 2=Test Case 3=Type 4=Priority 5=Status), used to pull real
# fixture values into TC-002/TC-003 instead of hardcoding them a second time.
pf_ptp_field_for_tc() {
  local file="$1" tc_id="$2" field_index="$3"
  pf_ptp_parse_rows "$file" | awk -F'\037' -v tc="$tc_id" -v fi="$field_index" '$1 == tc { print $fi }'
}

# pf_ptp_normalize_priority <raw Priority> — Phase 4.5 step 3, "Priority
# normalization": Critical->Critical, High->High, Medium->Med, Low->Low. Any
# other value normalizes to Med and carries a non-empty note (the original
# value) so an unrecognized priority doesn't silently vanish. Prints
# "Prio\037note" (note empty for dictionary hits).
pf_ptp_normalize_priority() {
  local raw="$1"
  case "$raw" in
    Critical) printf 'Critical\037' ;;
    High) printf 'High\037' ;;
    Medium) printf 'Med\037' ;;
    Low) printf 'Low\037' ;;
    *) printf 'Med\037original value: %s' "$raw" ;;
  esac
}

# pf_ptp_map_status <raw Status> — Phase 4.5 step 3 field-mapping table:
# [ ] -> pending, ✓ -> ✓, ✗ -> ✗.
pf_ptp_map_status() {
  case "$1" in
    "[ ]") printf 'pending' ;;
    "✓") printf '✓' ;;
    "✗") printf '✗' ;;
    *) printf '%s' "$1" ;;
  esac
}

# pf_ptp_last_run <mapped Status> <closing date> — Phase 4.5 step 3: "—" for
# pending, the issue's closing date otherwise.
pf_ptp_last_run() {
  local status="$1" closing_date="$2"
  if [ "$status" = "pending" ]; then
    printf '%s' '—'
  else
    printf '%s' "$closing_date"
  fi
}

# pf_ptp_phase45_section — the text of skills/pf-close/SKILL.md from its
# "## Phase 4.5" heading (inclusive) up to (exclusive) the next "## Phase "
# heading. Empty if Phase 4.5 does not exist yet.
pf_ptp_phase45_section() {
  awk '
    started && /^## Phase / { exit }
    /^## Phase 4\.5/ { started = 1 }
    started { print }
  ' "$PF_CLOSE_SKILL"
}

# ─── Helpers: PTC numbering (specs.md "Выделение номера", TC-004/005/006) ──

# pf_ptp_counter_value <docs/planning/test-plan.md file> — the integer encoded
# in its "Last allocated: PTC-NNNN" line, or 0 for "Last allocated: none" (the
# fresh-template state).
pf_ptp_counter_value() {
  local file="$1" line digits
  line="$(grep -m1 '^Last allocated:' "$file" 2>/dev/null || true)"
  case "$line" in
    *none*) printf '0' ;;
    *PTC-*)
      digits="$(printf '%s' "${line##*PTC-}" | tr -dc '0-9')"
      printf '%s' "$((10#${digits:-0}))"
      ;;
    *) printf '0' ;;
  esac
}

# pf_ptp_parse_global_rows <file> — one line per data row of the global
# test-plan.md table (header resolved by the literal "| PTC |" cell, not by a
# fixed line offset, so a fixture with extra prose above the table still
# parses). Fields joined by \037: PTC, Area, Test case, Prio, Origin, Last
# run, Status.
pf_ptp_parse_global_rows() {
  local file="$1"
  awk -F'|' '
    !header && /^\| *PTC *\|/ { header = 1; next }
    header && !sep && /^\| *-/ { sep = 1; next }
    header && sep && /^\|/ {
      ptc = $2; area = $3; tcase = $4; prio = $5; origin = $6; lastrun = $7; status = $8
      gsub(/^[ \t]+|[ \t]+$/, "", ptc)
      gsub(/^[ \t]+|[ \t]+$/, "", area)
      gsub(/^[ \t]+|[ \t]+$/, "", tcase)
      gsub(/^[ \t]+|[ \t]+$/, "", prio)
      gsub(/^[ \t]+|[ \t]+$/, "", origin)
      gsub(/^[ \t]+|[ \t]+$/, "", lastrun)
      gsub(/^[ \t]+|[ \t]+$/, "", status)
      if (ptc == "") next
      printf "%s\037%s\037%s\037%s\037%s\037%s\037%s\n", ptc, area, tcase, prio, origin, lastrun, status
    }
  ' "$file"
}

# pf_ptp_max_table_number <file> — highest PTC-NNNN numeric value already
# written in the table, or 0 for an empty table.
pf_ptp_max_table_number() {
  local file="$1" max=0 n digits
  while IFS= read -r n; do
    [ -z "$n" ] && continue
    digits="$(printf '%s' "${n#PTC-}" | tr -dc '0-9')"
    n="$((10#${digits:-0}))"
    [ "$n" -gt "$max" ] && max="$n"
  done < <(pf_ptp_parse_global_rows "$file" | awk -F'\037' '{ print $1 }')
  printf '%s' "$max"
}

# pf_ptp_next_number <file> — specs.md "Выделение номера": next PTC number is
# the maximum of (a) the Last allocated: counter and (b) the highest PTC
# already in the table, plus one. Formatted PTC-NNNN (4 digits).
pf_ptp_next_number() {
  local file="$1" counter table_max winner next
  counter="$(pf_ptp_counter_value "$file")"
  table_max="$(pf_ptp_max_table_number "$file")"
  winner="$counter"
  [ "$table_max" -gt "$winner" ] && winner="$table_max"
  next=$((winner + 1))
  printf 'PTC-%04d' "$next"
}

# pf_ptp_promote_row <file> <area> <test case> <prio> <origin> <last run>
# <status> — simulates Phase 4.5 steps 3-4 for exactly one Manual case:
# appends the new row with the number pf_ptp_next_number computes, then
# updates the Last allocated: line to that same number. Mutates <file> (a
# $TMP_WORK copy, never the read-only fixture — S-3). Prints the PTC assigned.
pf_ptp_promote_row() {
  local file="$1" area="$2" tcase="$3" prio="$4" origin="$5" lastrun="$6" status="$7"
  local ptc
  ptc="$(pf_ptp_next_number "$file")"
  printf '| %s | %s | %s | %s | %s | %s | %s |\n' \
    "$ptc" "$area" "$tcase" "$prio" "$origin" "$lastrun" "$status" >>"$file"
  sed -i "s/^Last allocated:.*/Last allocated: $ptc/" "$file"
  printf '%s' "$ptc"
}

# assert_numbering_rule_documented <step label> — shared drift-guard for
# TC-004/005/006 step 3 (test_plan.md: "тот же grep... с тем же сообщением,
# что TC-004 шаг 3" — one function so the wording never drifts between three
# copies). Greps the live Phase 4.5 text for the rule "next number = maximum
# of Last allocated: and the highest table PTC, plus one" (specs.md, Task 1
# pt. 4). The core diagnostic text is identical across all three callers; only
# the "<step label>:" prefix differs, per this suite's TC-ID-first convention.
assert_numbering_rule_documented() {
  local step_label="$1" sec45 has_rule=0
  sec45="$(pf_ptp_phase45_section)"
  if printf '%s\n' "$sec45" |
    grep -qiE 'maximum of.*\(a\).*Last allocated.*\(b\).*highest.*PTC.*table.*plus one'; then
    has_rule=1
  fi
  if [ "$has_rule" -eq 1 ]; then
    pf_pass "$step_label: Phase 4.5 documents the PTC numbering rule (max of Last allocated: and highest table PTC, plus one)"
  else
    pf_fail "$step_label: Phase 4.5 не документирует правило выделения номера"
  fi
}

# assert_number_format_documented <step label> — drift-guard for the WRITTEN FORM
# of an allocated number, which is a separate rule from the arithmetic above.
#
# Added after a real close found the gap: TC-014's live /pf-close run against a
# fresh list, on the revision of Phase 4.5 that documented only "maximum … plus
# one", wrote the row `| 1 | general | … |` and the counter `Last allocated: 1`.
# Arithmetically correct, and rejected by pf_validate_test_plan_file, which
# requires exactly four digits. Every Auto case here missed it because each one
# calls pf_ptp_next_number — a helper that TRANSCRIBES the intended formatting —
# so the suite agreed with itself while the skill text left the form unspecified.
# This guard reads the skill instead: it goes red if the written form (four
# digits, zero-padded) or the `none` == 0 seeding stops being documented.
assert_number_format_documented() {
  local step_label="$1" sec45 has_pad=0 has_none=0
  sec45="$(pf_ptp_phase45_section)"
  if printf '%s\n' "$sec45" | grep -qE 'PTC-0001' &&
    printf '%s\n' "$sec45" | grep -qiE 'four digits|4 digits'; then
    has_pad=1
  fi
  if printf '%s\n' "$sec45" | grep -qiE 'none.*counts as.*0|none.*as \*\*0\*\*'; then
    has_none=1
  fi
  if [ "$has_pad" -eq 1 ] && [ "$has_none" -eq 1 ]; then
    pf_pass "$step_label: Phase 4.5 documents the written form PTC-NNNN (four digits, zero-padded) and 'none' == 0"
  else
    pf_fail "$step_label: Phase 4.5 не документирует формат записи номера (PTC-NNNN, четыре цифры; 'none' == 0) — pad=$has_pad none=$has_none"
  fi
}

# ══════════════════════════════════════════════════════════════════════════════
printf '=== TC-001: only Type: Manual rows are ever selected for promotion (BR-1)\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-001: fixture test_plan.md not found: $TP_MIXED"
else
  selected="$(pf_ptp_select_manual "$TP_MIXED")"

  # Ground truth for step 2, computed independently of pf_ptp_select_manual /
  # pf_ptp_parse_rows by grepping the raw table for the literal Type cell — not
  # by re-running the helper under test, which would just compare it to itself.
  n_manual_raw="$(grep -cE '\| *Manual *\|' "$TP_MIXED")"
  n_auto_raw="$(grep -cE '\| *Auto *\|' "$TP_MIXED")"

  n_selected="$(printf '%s\n' "$selected" | grep -c . || true)"
  n_selected_auto="$(printf '%s\n' "$selected" | awk -F'\037' '$3 == "Auto"' | grep -c . || true)"

  if [ "$n_auto_raw" -ge 1 ] && [ "$n_manual_raw" -ge 2 ] && [ "$n_selected_auto" -eq 0 ]; then
    pf_pass "TC-001 step 1: selection contains no Type: Auto row ($n_auto_raw Auto row(s) in fixture, correctly excluded)"
  else
    pf_fail "TC-001 step 1: an Auto row leaked into the selection, or fixture preconditions unmet (auto_raw=$n_auto_raw manual_raw=$n_manual_raw selected_auto=$n_selected_auto)"
  fi

  if [ "$n_selected" -eq "$n_manual_raw" ]; then
    pf_pass "TC-001 step 2: selected row count ($n_selected) equals the fixture's Type: Manual row count ($n_manual_raw)"
  else
    pf_fail "TC-001 step 2: selection returned $n_selected rows, fixture has $n_manual_raw Type: Manual rows"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_manual_rule=0
  has_auto_excluded=0
  printf '%s\n' "$sec45" | grep -qiE 'Type.{0,10}(is|:).{0,10}Manual' && has_manual_rule=1
  printf '%s\n' "$sec45" | grep -qF 'Type: Auto' && has_auto_excluded=1
  if [ "$has_manual_rule" -eq 1 ] && [ "$has_auto_excluded" -eq 1 ]; then
    pf_pass "TC-001 step 3: Phase 4.5 documents selecting Type: Manual rows and excluding Type: Auto rows"
  else
    pf_fail "TC-001 step 3: Phase 4.5 не документирует отбор по Type: Manual (selection rule found: $has_manual_rule, Auto-exclusion found: $has_auto_excluded)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-002: Priority normalization, including Medium -> Med and the off-dictionary fallback\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-002: fixture test_plan.md not found: $TP_MIXED"
else
  prio_critical="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-002" 4)"
  prio_high="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-003" 4)"
  prio_medium="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-004" 4)"
  prio_low="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-005" 4)"
  prio_offdict="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-006" 4)"

  out_critical="$(pf_ptp_normalize_priority "$prio_critical")"
  out_high="$(pf_ptp_normalize_priority "$prio_high")"
  out_medium="$(pf_ptp_normalize_priority "$prio_medium")"
  out_low="$(pf_ptp_normalize_priority "$prio_low")"

  ok_std=1
  [ "${out_critical%%$'\037'*}" = "Critical" ] || ok_std=0
  [ "${out_high%%$'\037'*}" = "High" ] || ok_std=0
  [ "${out_medium%%$'\037'*}" = "Med" ] || ok_std=0
  [ "${out_low%%$'\037'*}" = "Low" ] || ok_std=0

  if [ "$ok_std" -eq 1 ]; then
    pf_pass "TC-002 step 1: Critical/High/Medium/Low normalize to Critical/High/Med/Low"
  else
    pf_fail "TC-002 step 1: normalization mismatch (Critical->${out_critical%%$'\037'*}, High->${out_high%%$'\037'*}, Medium->${out_medium%%$'\037'*}, Low->${out_low%%$'\037'*})"
  fi

  out_offdict="$(pf_ptp_normalize_priority "$prio_offdict")"
  offdict_prio="${out_offdict%%$'\037'*}"
  offdict_note="${out_offdict#*$'\037'}"
  if [ "$offdict_prio" = "Med" ] && [ -n "$offdict_note" ]; then
    pf_pass "TC-002 step 2: off-dictionary value '$prio_offdict' carries through as Med, noted ($offdict_note)"
  else
    pf_fail "TC-002 step 2: off-dictionary value '$prio_offdict' -> prio='$offdict_prio' note='$offdict_note' (want Med + non-empty note)"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_medium_med=0
  has_offdict_rule=0
  printf '%s\n' "$sec45" | grep -qiE 'Medium.{0,10}(→|->).{0,10}Med' && has_medium_med=1
  printf '%s\n' "$sec45" | grep -qiE 'outside.{0,20}dictionary.{0,40}Med' && has_offdict_rule=1
  if [ "$has_medium_med" -eq 1 ] && [ "$has_offdict_rule" -eq 1 ]; then
    pf_pass "TC-002 step 3: Phase 4.5 documents Medium -> Med and the off-dictionary fallback"
  else
    pf_fail "TC-002 step 3: Phase 4.5 не документирует нормализацию Priority → Prio (Medium->Med found: $has_medium_med, off-dictionary rule found: $has_offdict_rule)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-003: Status mapping [ ] -> pending, ✓ -> ✓, ✗ -> ✗\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_MIXED" ]; then
  pf_fail "TC-003: fixture test_plan.md not found: $TP_MIXED"
else
  status_pending_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-002" 5)"
  status_pass_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-003" 5)"
  status_fail_raw="$(pf_ptp_field_for_tc "$TP_MIXED" "TC-004" 5)"

  mapped_pending="$(pf_ptp_map_status "$status_pending_raw")"
  mapped_pass="$(pf_ptp_map_status "$status_pass_raw")"
  mapped_fail="$(pf_ptp_map_status "$status_fail_raw")"

  if [ "$mapped_pending" = "pending" ]; then
    pf_pass "TC-003 step 1: '$status_pending_raw' maps to pending"
  else
    pf_fail "TC-003 step 1: '$status_pending_raw' mapped to '$mapped_pending' (want pending)"
  fi
  if [ "$mapped_pass" = "✓" ]; then
    pf_pass "TC-003 step 2: '$status_pass_raw' maps to ✓"
  else
    pf_fail "TC-003 step 2: '$status_pass_raw' mapped to '$mapped_pass' (want ✓)"
  fi
  if [ "$mapped_fail" = "✗" ]; then
    pf_pass "TC-003 step 3: '$status_fail_raw' maps to ✗"
  else
    pf_fail "TC-003 step 3: '$status_fail_raw' mapped to '$mapped_fail' (want ✗)"
  fi

  CLOSING_DATE="2026-08-11"
  lr_pending="$(pf_ptp_last_run "$mapped_pending" "$CLOSING_DATE")"
  lr_pass="$(pf_ptp_last_run "$mapped_pass" "$CLOSING_DATE")"
  lr_fail="$(pf_ptp_last_run "$mapped_fail" "$CLOSING_DATE")"
  if [ "$lr_pending" = "—" ] && [ "$lr_pass" = "$CLOSING_DATE" ] && [ "$lr_fail" = "$CLOSING_DATE" ]; then
    pf_pass "TC-003 step 4: Last run is — for pending and the closing date for ✓/✗"
  else
    pf_fail "TC-003 step 4: Last run mismatch (pending='$lr_pending' want '—'; pass='$lr_pass' fail='$lr_fail' want '$CLOSING_DATE')"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_status_table=0
  has_source_form=0
  has_target_form=0
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF '`[ ]` / `✓` / `✗`' && has_source_form=1
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF '`pending` / `✓` / `✗`' && has_target_form=1
  if [ "$has_source_form" -eq 1 ] && [ "$has_target_form" -eq 1 ]; then
    has_status_table=1
  fi
  has_lastrun_rule=0
  printf '%s\n' "$sec45" | grep -qiE 'Last run.{0,20}—.{0,20}pending' && has_lastrun_rule=1
  if [ "$has_status_table" -eq 1 ] && [ "$has_lastrun_rule" -eq 1 ]; then
    pf_pass "TC-003 step 5: Phase 4.5 documents the [ ]/✓/✗ -> pending/✓/✗ mapping and the Last run rule"
  else
    pf_fail "TC-003 step 5: Phase 4.5 не документирует отображение статусов (status table found: $has_status_table, Last run rule found: $has_lastrun_rule)"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-013: /pf-close phase order and Phase 8 archive-commit composition\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$PF_CLOSE_SKILL" ]; then
  pf_fail "TC-013: skills/pf-close/SKILL.md does not exist"
else
  line_phase4="$(grep -n '^## Phase 4: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase45="$(grep -n '^## Phase 4\.5$' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase5="$(grep -n '^## Phase 5: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

  if [ -n "$line_phase4" ] && [ -n "$line_phase45" ] && [ -n "$line_phase5" ] &&
    [ "$line_phase4" -lt "$line_phase45" ] && [ "$line_phase45" -lt "$line_phase5" ]; then
    pf_pass "TC-013 step 1: ## Phase 4 (line $line_phase4) < ## Phase 4.5 (line $line_phase45) < ## Phase 5 (line $line_phase5)"
  else
    pf_fail "TC-013 step 1: Phase 4/4.5/5 headings missing or out of order (Phase4=${line_phase4:-<missing>} Phase4.5=${line_phase45:-<missing>} Phase5=${line_phase5:-<missing>})"
  fi

  line_phase8="$(grep -n '^## Phase 8: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_phase85="$(grep -n '^## Phase 8\.5: ' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

  if [ -z "$line_phase8" ]; then
    pf_fail "TC-013 step 2: ## Phase 8: heading not found"
  else
    if [ -n "$line_phase85" ]; then
      phase8_section="$(sed -n "${line_phase8},$((line_phase85 - 1))p" "$PF_CLOSE_SKILL")"
    else
      phase8_section="$(sed -n "${line_phase8},\$p" "$PF_CLOSE_SKILL")"
    fi
    if printf '%s\n' "$phase8_section" | grep -qF 'git add' &&
      printf '%s\n' "$phase8_section" | grep -qF 'docs/planning/test-plan.md'; then
      pf_pass "TC-013 step 2: Phase 8's git add includes docs/planning/test-plan.md"
    else
      pf_fail "TC-013 step 2: Phase 8's git add line does not include docs/planning/test-plan.md"
    fi
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-004: PTC numbering on a fresh/empty docs/planning/test-plan.md\n'
# ══════════════════════════════════════════════════════════════════════════════

tp004="$(pf_ptp_case_file "$PTP_FIX_FRESH")"

if [ ! -f "$tp004" ]; then
  pf_fail "TC-004: fixture docs/planning/test-plan.md not found ($PTP_FIX_FRESH)"
else
  next004="$(pf_ptp_next_number "$tp004")"
  if [ "$next004" = "PTC-0001" ]; then
    pf_pass "TC-004 step 1: numbering on an empty table yields PTC-0001"
  else
    pf_fail "TC-004 step 1: numbering on an empty table yielded $next004, want PTC-0001"
  fi

  assigned004="$(pf_ptp_promote_row "$tp004" "explorer-ui" \
    "Тема сохраняется между перезагрузками страницы" "High" \
    "20990101-feat-fixture-mixed#TC-005" "—" "pending")"
  last_alloc004="$(pf_ptp_counter_value "$tp004")"
  row_count004="$(pf_ptp_parse_global_rows "$tp004" | grep -c . || true)"

  if [ "$assigned004" = "PTC-0001" ] && [ "$last_alloc004" -eq 1 ] && [ "$row_count004" -eq 1 ]; then
    pf_pass "TC-004 step 2: promoting one Manual case onto the fresh file gets PTC-0001 and Last allocated: is updated to it"
  else
    pf_fail "TC-004 step 2: promotion assigned '$assigned004' (want PTC-0001), Last allocated: now $last_alloc004, row count $row_count004"
  fi
fi

assert_numbering_rule_documented "TC-004 step 3"
assert_number_format_documented "TC-004 step 4"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-005: PTC numbering after a retired row was deleted by hand (counter wins)\n'
# ══════════════════════════════════════════════════════════════════════════════

tp005="$(pf_ptp_case_file "$PTP_FIX_RETIRED_DELETED")"

if [ ! -f "$tp005" ]; then
  pf_fail "TC-005: fixture docs/planning/test-plan.md not found ($PTP_FIX_RETIRED_DELETED)"
else
  counter005="$(pf_ptp_counter_value "$tp005")"
  table_max005="$(pf_ptp_max_table_number "$tp005")"
  next005="$(pf_ptp_next_number "$tp005")"

  if [ "$counter005" -eq 7 ] && [ "$table_max005" -eq 5 ] && [ "$next005" = "PTC-0008" ]; then
    pf_pass "TC-005 step 1: max(Last allocated: PTC-0007, table max PTC-0005) + 1 = PTC-0008, not PTC-0006"
  else
    pf_fail "TC-005 step 1: counter=$counter005 table_max=$table_max005 next=$next005 (want counter=7 table_max=5 next=PTC-0008)"
  fi

  assigned005="$(pf_ptp_promote_row "$tp005" "pf-close" \
    "Восстановление после сбоя в середине Phase 4.5" "Critical" \
    "20990101-feat-fixture-mixed#TC-006" "—" "pending")"
  n_0006="$(grep -c 'PTC-0006' "$tp005" || true)"
  n_0007="$(grep -c 'PTC-0007' "$tp005" || true)"

  if [ "$assigned005" = "PTC-0008" ] && [ "$n_0006" -eq 0 ] && [ "$n_0007" -eq 0 ]; then
    pf_pass "TC-005 step 2: new row got PTC-0008; PTC-0006/PTC-0007 (deleted retired rows) do not reappear"
  else
    pf_fail "TC-005 step 2: new row got '$assigned005' (want PTC-0008); PTC-0006 occurrences=$n_0006 PTC-0007 occurrences=$n_0007 (want 0/0)"
  fi
fi

assert_numbering_rule_documented "TC-005 step 3"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-006: PTC numbering with a stale counter behind written rows (table wins)\n'
# ══════════════════════════════════════════════════════════════════════════════

tp006="$(pf_ptp_case_file "$PTP_FIX_STALE_COUNTER")"

if [ ! -f "$tp006" ]; then
  pf_fail "TC-006: fixture docs/planning/test-plan.md not found ($PTP_FIX_STALE_COUNTER)"
else
  counter006="$(pf_ptp_counter_value "$tp006")"
  table_max006="$(pf_ptp_max_table_number "$tp006")"
  next006="$(pf_ptp_next_number "$tp006")"

  if [ "$counter006" -eq 3 ] && [ "$table_max006" -eq 5 ] && [ "$next006" = "PTC-0006" ]; then
    pf_pass "TC-006 step 1: max(Last allocated: PTC-0003, table max PTC-0005) + 1 = PTC-0006, not PTC-0004"
  else
    pf_fail "TC-006 step 1: counter=$counter006 table_max=$table_max006 next=$next006 (want counter=3 table_max=5 next=PTC-0006)"
  fi

  assigned006="$(pf_ptp_promote_row "$tp006" "scripts" \
    "Идемпотентность повторного запуска Phase 4.5 при одинаковых названиях" "High" \
    "20990101-feat-fixture-mixed#TC-007" "—" "pending")"
  last_alloc006="$(pf_ptp_counter_value "$tp006")"

  if [ "$assigned006" = "PTC-0006" ] && [ "$last_alloc006" -eq 6 ]; then
    pf_pass "TC-006 step 2: new row got PTC-0006 (not a re-issue of an existing row's number) and Last allocated: is updated to it"
  else
    pf_fail "TC-006 step 2: new row got '$assigned006' (want PTC-0006), Last allocated: now $last_alloc006 (want 6)"
  fi
fi

assert_numbering_rule_documented "TC-006 step 3"

# ─── Insertion point ────────────────────────────────────────────────────────
# Tasks 4-7 of this issue (TC-007..TC-012, TC-015, TC-017..TC-019) each add
# their own "=== TC-NNN: ... ===" section HERE — ABOVE assert_repo_untouched /
# pf_summary below, never below them. pf_summary only tallies PASS/FAIL calls
# made before it runs; appending a new TC section after it would make that
# section's results invisible to the suite's exit code.

# ─── pf_validate_test_plan_file: shared row-shape validator (Task 4) ───────
# Defined here, ABOVE its first call (TC-007 below), on purpose: Task 5's
# TC-009 and Task 7's TC-018/TC-019 call this same function later in this
# file, and this suite executes top to bottom in one interpreter pass — the
# definition must physically precede every call site (implementation_plan.md
# Task 4 note on task ordering). Nothing here is a stub; this is the one real
# implementation all four call sites share.

# _pf_ptp_trim <string> — strip leading/trailing whitespace from one table
# cell after it has been split out of a row.
_pf_ptp_trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

# pf_validate_test_plan_file <path to a docs/planning/test-plan.md-shaped file>
#
# Read-only structural validator for the global list's format (specs.md "Data
# model", "Устойчивость к ручной правке"). Contract:
#   - Never writes to <path> — TC-019 (Task 7) diffs the file before/after a
#     run to prove this.
#   - Prints one diagnostic line per violation to stdout, each naming the
#     concrete rule broken (a duplicate PTC number and its value, the bad
#     field and the value it held, or the missing counter line) — never a
#     generic "invalid file".
#   - Returns 0 iff zero violations were found (a well-formed file with zero
#     data rows, e.g. the fresh template, is valid). Returns 1 otherwise,
#     including when <path> itself does not exist.
# Checks performed, in specs.md order: (1) a "Last allocated:" counter line
# exists above the table; (2) every data row splits into exactly 7 fields
# (PTC | Area | Test case | Prio | Origin | Last run | Status) once `\|`
# escape sequences are masked out of the split — an escaped pipe inside Area/
# Test case/Origin must never be mistaken for a column boundary; (3) `PTC` is
# exactly `PTC-NNNN` (4 digits); (4) no two rows share the same `PTC` (BR-2's
# uniqueness is DETECTED post-hoc here, deliberately not prevented at write
# time — specs.md: two branches promoting in parallel both write the same
# next number and git merges that silently, so the first `make test` after
# the merge is where this is meant to be caught); (5) `Prio` is one of the
# closed dictionary {Critical, High, Med, Low}; (6) `Status` is one of the
# closed dictionary {pending, ✓, ✗, retired}.
pf_validate_test_plan_file() {
  local file="$1"
  local ok=0
  local seen_ptcs=$'\002'

  if [ ! -f "$file" ]; then
    printf 'file not found: %s\n' "$file"
    return 1
  fi

  if ! grep -q '^Last allocated:' "$file"; then
    printf 'missing "Last allocated:" counter line above the table\n'
    ok=1
  fi

  local header_done=0 sep_done=0 rawline masked needle n_fields
  local ptc prio status
  local -a cells
  while IFS= read -r rawline; do
    if [ "$header_done" -eq 0 ]; then
      if [[ "$rawline" =~ ^\|[[:space:]]*PTC[[:space:]]*\| ]]; then
        header_done=1
      fi
      continue
    fi
    if [ "$sep_done" -eq 0 ]; then
      if [[ "$rawline" =~ ^\|[[:space:]]*-{2,} ]]; then
        sep_done=1
      fi
      continue
    fi
    [[ "$rawline" =~ ^\| ]] || continue

    # Mask \| before splitting on | — an escaped pipe inside a cell (specs.md:
    # "|" in Area/Test case/Origin is written as "\|") is not a column
    # boundary. Unmasking isn't needed below: only PTC/Prio/Status are
    # inspected, and none of those three ever legitimately contains a pipe.
    masked="${rawline//\\|/$'\001'}"
    IFS='|' read -ra cells <<<"$masked"
    n_fields=$(( ${#cells[@]} - 1 )) # cells[0] is the empty slot before the leading "|"
    if [ "$n_fields" -ne 7 ]; then
      printf 'row has %d field(s), expected 7 (PTC | Area | Test case | Prio | Origin | Last run | Status): %s\n' \
        "$n_fields" "$rawline"
      ok=1
      continue
    fi

    ptc="$(_pf_ptp_trim "${cells[1]}")"
    prio="$(_pf_ptp_trim "${cells[4]}")"
    status="$(_pf_ptp_trim "${cells[7]}")"

    if [[ ! "$ptc" =~ ^PTC-[0-9]{4}$ ]]; then
      printf "PTC field '%s' does not match PTC-NNNN (exactly 4 digits): %s\n" "$ptc" "$rawline"
      ok=1
    fi

    needle=$'\002'"$ptc"$'\002'
    case "$seen_ptcs" in
      *"$needle"*)
        printf 'duplicate PTC %s found (row: %s)\n' "$ptc" "$rawline"
        ok=1
        ;;
      *) seen_ptcs="${seen_ptcs}${ptc}"$'\002' ;;
    esac

    case "$prio" in
      Critical | High | Med | Low) : ;;
      *)
        printf "Prio value '%s' outside the closed dictionary (Critical|High|Med|Low): %s\n" "$prio" "$rawline"
        ok=1
        ;;
    esac

    case "$status" in
      pending | "✓" | "✗" | retired) : ;;
      *)
        printf "Status value '%s' outside the closed dictionary (pending|✓|✗|retired): %s\n" "$status" "$rawline"
        ok=1
        ;;
    esac
  done <"$file"

  return "$ok"
}

PTP_SUITE_SELF="$REPO_ROOT/test/pf-product-test-plan.sh"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-007: a duplicate PTC across two rows is detected, not prevented\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$PTP_SUITE_SELF" ]; then
  pf_fail "TC-007 step 1: test/pf-product-test-plan.sh ещё не создан (задача реализации)"
else
  pf_pass "TC-007 step 1: test/pf-product-test-plan.sh существует"

  tp007="$(pf_ptp_case_file "global-duplicate-ptc")"
  if [ ! -f "$tp007" ]; then
    pf_fail "TC-007: fixture docs/planning/test-plan.md not found (global-duplicate-ptc)"
  else
    out007="$(pf_validate_test_plan_file "$tp007" 2>&1)"
    rc007=$?

    if [ "$rc007" -ne 0 ]; then
      pf_pass "TC-007 step 2: validator exits non-zero on a table containing two PTC-0012 rows"
    else
      pf_fail "TC-007 step 2: детектор дублей PTC не реализован — validator exited 0 on a duplicate PTC-0012"
    fi

    if printf '%s\n' "$out007" | grep -qF 'PTC-0012'; then
      pf_pass "TC-007 step 3: validator output names the duplicated number PTC-0012"
    else
      pf_fail "TC-007 step 3: детектор дублей PTC не реализован — output does not name PTC-0012 (got: $out007)"
    fi
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-008: row shape and the closed Prio/Status dictionaries\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$PTP_SUITE_SELF" ]; then
  pf_fail "TC-008 step 1: test/pf-product-test-plan.sh ещё не создан (задача реализации)"
else
  pf_pass "TC-008 step 1: test/pf-product-test-plan.sh существует"

  tp008_prio="$(pf_ptp_case_file "global-malformed-rows/prio-bad")"
  if [ ! -f "$tp008_prio" ]; then
    pf_fail "TC-008 step 2: fixture not found (global-malformed-rows/prio-bad)"
  else
    out="$(pf_validate_test_plan_file "$tp008_prio" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'Prio'; then
      pf_pass "TC-008 step 2: validator rejects 'Prio: Medium' (outside Critical/High/Med/Low), naming the Prio field ($out)"
    else
      pf_fail "TC-008 step 2: валидация Prio не реализована (rc=$rc, output: $out)"
    fi
  fi

  tp008_status="$(pf_ptp_case_file "global-malformed-rows/status-bad")"
  if [ ! -f "$tp008_status" ]; then
    pf_fail "TC-008 step 3: fixture not found (global-malformed-rows/status-bad)"
  else
    out="$(pf_validate_test_plan_file "$tp008_status" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'Status'; then
      pf_pass "TC-008 step 3: validator rejects 'Status: Passed' (a made-up value), naming the Status field ($out)"
    else
      pf_fail "TC-008 step 3: валидация Status не реализована (rc=$rc, output: $out)"
    fi
  fi

  tp008_ptc="$(pf_ptp_case_file "global-malformed-rows/ptc-bad")"
  if [ ! -f "$tp008_ptc" ]; then
    pf_fail "TC-008 step 4: fixture not found (global-malformed-rows/ptc-bad)"
  else
    out="$(pf_validate_test_plan_file "$tp008_ptc" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'PTC-12'; then
      pf_pass "TC-008 step 4: validator rejects the malformed number PTC-12 (not 4 digits), naming the bad form ($out)"
    else
      pf_fail "TC-008 step 4: валидация формы PTC не реализована (rc=$rc, output: $out)"
    fi
  fi

  tp008_nocounter="$(pf_ptp_case_file "global-malformed-rows/no-counter")"
  if [ ! -f "$tp008_nocounter" ]; then
    pf_fail "TC-008 step 5: fixture not found (global-malformed-rows/no-counter)"
  else
    out="$(pf_validate_test_plan_file "$tp008_nocounter" 2>&1)"
    rc=$?
    if [ "$rc" -ne 0 ] && printf '%s\n' "$out" | grep -qF 'Last allocated'; then
      pf_pass "TC-008 step 5: validator rejects a table with no 'Last allocated:' line above it, naming the missing counter ($out)"
    else
      pf_fail "TC-008 step 5: проверка наличия Last allocated: не реализована (rc=$rc, output: $out)"
    fi
  fi
fi

# ─── Helpers: escaping `|` on write, reading a source cell that already
# carries the same escape (TC-009) ──────────────────────────────────────────

# pf_ptp_escape_pipe <string> — Phase 4.5 "Escaping": any "|" is written as
# "\|" when a row is appended to the global list.
pf_ptp_escape_pipe() {
  local s="$1"
  printf '%s' "${s//|/\\|}"
}

# pf_ptp_read_manual_field <issue test_plan.md> <TC-NNN> <column 1..6> — like
# TC-001..003's pf_ptp_field_for_tc, but masks `\|` before splitting on `|` so
# a Test case title that itself contains an escaped pipe (valid: the issue's
# own Status Tracker table needs that same escape, or ITS table would not
# parse either) does not shift every column after it. Column order fixed to
# this fixture's own header (TC | Test Case | Type | Priority | Status |
# Remarks) — narrower than pf_ptp_parse_rows on purpose, since that helper's
# unmasked split is exactly what a `|`-bearing title would break. Prints the
# trimmed cell with the escape UNMASKED back to a real "|".
pf_ptp_read_manual_field() {
  local file="$1" tc="$2" col="$3" rawline masked cell
  local -a cells
  rawline="$(grep -E "^\| *${tc} *\|" "$file" | head -1)"
  if [ -z "$rawline" ]; then
    return 1
  fi
  masked="${rawline//\\|/$'\001'}"
  IFS='|' read -ra cells <<<"$masked"
  cell="$(_pf_ptp_trim "${cells[$col]}")"
  printf '%s' "${cell//$'\001'/|}"
}

TP_PIPES="$REPO_ROOT/test/fixtures/pf-product-test-plan/issue-pipe-in-fields/docs/issues/open/20990101-feat-fixture-pipes/test_plan.md"
PIPE_ISSUE_ID="20990101-feat-fixture-pipes"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-009: | in Area/Test case/Origin survives write and re-parse\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_PIPES" ]; then
  pf_fail "TC-009: fixture test_plan.md not found: $TP_PIPES"
else
  raw_title="$(pf_ptp_read_manual_field "$TP_PIPES" "TC-001" 2)"
  prio_raw="$(pf_ptp_read_manual_field "$TP_PIPES" "TC-001" 4)"
  status_raw="$(pf_ptp_read_manual_field "$TP_PIPES" "TC-001" 5)"

  if printf '%s' "$raw_title" | grep -qF '|'; then
    pf_pass "TC-009 setup: fixture title read back with its real | intact ('$raw_title')"
  else
    pf_fail "TC-009 setup: fixture title lost its | on read (got '$raw_title')"
  fi

  escaped_title="$(pf_ptp_escape_pipe "$raw_title")"
  prio_out="$(pf_ptp_normalize_priority "$prio_raw")"
  prio_norm="${prio_out%%$'\037'*}"
  status_mapped="$(pf_ptp_map_status "$status_raw")"
  lastrun009="$(pf_ptp_last_run "$status_mapped" "2026-08-11")"
  origin009="${PIPE_ISSUE_ID}#TC-001"

  target009="$(pf_ptp_case_file "$PTP_FIX_FRESH")"
  if [ ! -f "$target009" ]; then
    pf_fail "TC-009: fixture docs/planning/test-plan.md not found ($PTP_FIX_FRESH)"
  else
    assigned009="$(pf_ptp_promote_row "$target009" "explorer-ui" "$escaped_title" \
      "$prio_norm" "$origin009" "$lastrun009" "$status_mapped")"

    # Anchored on a leading "| PTC-NNNN |" so the "Last allocated: PTC-NNNN"
    # counter line (which legitimately repeats the same PTC value) is never
    # mistaken for a second data row.
    row_line009="$(grep -E "^\| *${assigned009} *\|" "$target009" | head -1)"
    n_rows_with_ptc="$(grep -cE "^\| *${assigned009} *\|" "$target009" || true)"
    n_pipe_raw="$(printf '%s' "$raw_title" | grep -o -F '|' | grep -c . || true)"
    n_pipe_escaped_written="$(printf '%s' "$row_line009" | grep -o -F '\|' | grep -c . || true)"

    if [ "$n_rows_with_ptc" -eq 1 ] && [ "$n_pipe_escaped_written" -eq "$n_pipe_raw" ] && [ "$n_pipe_raw" -gt 0 ]; then
      pf_pass "TC-009 step 1: all $n_pipe_raw '|' char(s) written as \\| in a single row, field count unchanged"
    else
      pf_fail "TC-009 step 1: row count=$n_rows_with_ptc, raw '|' count=$n_pipe_raw, escaped '\\|' count written=$n_pipe_escaped_written (want row count=1, both counts equal and >0)"
    fi

    out009="$(pf_validate_test_plan_file "$target009" 2>&1)"
    rc009=$?
    if [ "$rc009" -eq 0 ]; then
      pf_pass "TC-009 step 2: pf_validate_test_plan_file parses the escaped row as one valid 7-field row"
    else
      pf_fail "TC-009 step 2: pf_validate_test_plan_file rejected the escaped row: $out009"
    fi
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_escape_targets=0
  has_escape_form=0
  printf '%s\n' "$sec45" | grep -qE 'Area.*Test case.*Origin' && has_escape_targets=1
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF 'written as `\|`' && has_escape_form=1
  if [ "$has_escape_targets" -eq 1 ] && [ "$has_escape_form" -eq 1 ]; then
    pf_pass "TC-009 step 3: Phase 4.5 documents escaping | as \\| in Area/Test case/Origin"
  else
    pf_fail "TC-009 step 3: Phase 4.5 не документирует экранирование \\| (targets found: $has_escape_targets, form found: $has_escape_form)"
  fi
fi

# ─── Helpers: Area by merge-commit diff (TC-010) ───────────────────────────

# pf_ptp_area_diff_files <repo dir> — Phase 4.5 "Area": the two-parent form of
# the merge-commit diff, NOT the three-dot <parent>...<issue-branch> form
# (specs.md/SKILL.md: after Phase 4's --no-ff merge, the three-dot merge-base
# has become the tip of the issue branch itself, so that diff is always
# empty). HEAD is the fresh merge commit; HEAD^1 is the parent branch tip
# before the merge, HEAD^2 is the tip of issue/ISSUE-ID.
pf_ptp_area_diff_files() {
  git -C "$1" diff --name-only 'HEAD^1' 'HEAD^2'
}

# pf_ptp_area_exclude_docs_issues — drops any path under docs/issues/ from a
# newline-separated list on stdin (the issue's own planning docs don't
# describe a subsystem).
pf_ptp_area_exclude_docs_issues() {
  grep -vE '^docs/issues/'
}

# pf_ptp_area_segment <path> — second path segment for anything under
# skills/ or tools/, first segment for everything else.
pf_ptp_area_segment() {
  local path="$1"
  case "$path" in
    skills/*/* | tools/*/*)
      path="${path#*/}"
      printf '%s' "${path%%/*}"
      ;;
    *)
      printf '%s' "${path%%/*}"
      ;;
  esac
}

# pf_ptp_area_winner — reads paths from stdin (already docs/issues/-excluded),
# segments each with pf_ptp_area_segment, and prints the segment with the
# most files; "general" if stdin has no non-empty lines.
pf_ptp_area_winner() {
  local -A counts=()
  local path seg best="" best_n=-1
  while IFS= read -r path; do
    [ -z "$path" ] && continue
    seg="$(pf_ptp_area_segment "$path")"
    counts[$seg]=$((${counts[$seg]:-0} + 1))
  done
  if [ ${#counts[@]} -eq 0 ]; then
    printf 'general'
    return 0
  fi
  for seg in "${!counts[@]}"; do
    if [ "${counts[$seg]}" -gt "$best_n" ]; then
      best_n="${counts[$seg]}"
      best="$seg"
    fi
  done
  printf '%s' "$best"
}

# pf_ptp_area_setup — a --git case-setup for the "area-diff-repo" fixture,
# built locally instead of calling `pf_setup_case "pf-product-test-plan/
# area-diff-repo" --git`. pf_setup_case's `cp -a "$src" "$parent/$fixture"`
# needs the destination's INTERMEDIATE directory to already exist, which it
# does not for a fixture name containing a slash (the same bug
# pf_ptp_case_file's header comment documents for global-fresh and friends).
# Flattening the destination to the single leaf "area-diff-repo" (no slash)
# avoids the bug; pf_git_init (test/lib.sh) gives the same baseline commit
# --git would. Prints the path, or nothing (rc 1) if the fixture directory
# itself is missing — callers MUST check the result before using it in any
# git -C command: an empty path there silently targets the caller's cwd
# instead of a throwaway repo, which is exactly the failure mode this
# function exists to make impossible.
pf_ptp_area_setup() {
  local src="$PF_FIXTURES_DIR/pf-product-test-plan/area-diff-repo"
  if [ ! -d "$src" ]; then
    return 1
  fi
  local parent work
  parent="$(pf_mktemp_d)" || return 1
  work="$parent/area-diff-repo"
  cp -a "$src" "$work"
  pf_git_init "$work"
  printf '%s' "$work"
}

AREA_ID="20990101-feat-fixture-area"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-010: Area is derived from the merge-commit diff, docs/issues/ excluded\n'
# ══════════════════════════════════════════════════════════════════════════════
# Builds develop + issue/<ID>, edits the 4 files on the issue branch, then
# performs the SAME --no-ff merge Phase 4 performs BEFORE computing the diff
# (implementation_plan.md Task 5 / P1-A review): a fixture that diffed the
# pre-merge graph would pass even if Phase 4.5 used the three-dot form, which
# is empty after a real --no-ff merge and would never be diagnostic.
area_d="$(pf_ptp_area_setup)"

if [ -z "$area_d" ] || [ ! -d "$area_d" ]; then
  # Guarded on purpose (S-5): every git command below is scoped to this
  # branch so a setup failure can never fall through to a `git -C ""` that
  # silently operates on the caller's cwd instead of a throwaway repo.
  pf_fail "TC-010: area-diff-repo fixture setup failed (fixture directory missing or pf_mktemp_d failed)"
  pf_fail "TC-010 step 1: skipped — fixture setup failed"
  pf_fail "TC-010 step 2: skipped — fixture setup failed"
  pf_fail "TC-010 step 3: skipped — fixture setup failed"
  pf_fail "TC-010 step 4: skipped — fixture setup failed"
else
  git -C "$area_d" branch develop
  git -C "$area_d" checkout -q -b "issue/$AREA_ID" develop
  mkdir -p "$area_d/skills/pf-close" "$area_d/scripts" "$area_d/docs/issues/open/$AREA_ID"
  printf '# probe SKILL.md edit\n' >"$area_d/skills/pf-close/SKILL.md"
  printf '# probe new file\n' >"$area_d/skills/pf-close/foo.md"
  printf '# probe scripts/ edit\n' >"$area_d/scripts/build.sh"
  printf '# probe issue specs.md\n' >"$area_d/docs/issues/open/$AREA_ID/specs.md"
  git -C "$area_d" add -A
  git -C "$area_d" -c user.name='PF Test' -c user.email='pf-test@example.invalid' \
    commit -q -m "issue changes for TC-010"
  git -C "$area_d" checkout -q develop
  git -C "$area_d" -c user.name='PF Test' -c user.email='pf-test@example.invalid' \
    merge -q --no-ff "issue/$AREA_ID" -m "merge: close $AREA_ID"

  # The discriminating check this fixture exists for (specs.md / SKILL.md
  # Phase 4.5 step 5, measured on a real close: three-dot gives 0 files after
  # a --no-ff merge because merge-base(develop, issue/ID) has become the
  # issue branch's own tip, while the two-parent form gives the real set).
  # Asserted here, not just narrated, so a fixture that silently DIDN'T
  # reproduce the degenerate post-merge graph (e.g. an accidental fast-forward
  # merge) would be caught by this line, not misread as "Area works".
  threedot010="$(git -C "$area_d" diff --name-only "develop...issue/$AREA_ID")"
  n_threedot010="$(printf '%s\n' "$threedot010" | grep -c . || true)"

  diff010="$(pf_ptp_area_diff_files "$area_d")"
  n_diff010="$(printf '%s\n' "$diff010" | grep -c . || true)"
  has_docs_issues010=0
  printf '%s\n' "$diff010" | grep -qE '^docs/issues/' && has_docs_issues010=1
  if [ "$n_threedot010" -eq 0 ] && [ "$n_diff010" -eq 4 ] && [ "$has_docs_issues010" -eq 1 ]; then
    pf_pass "TC-010 step 1: three-dot develop...issue/$AREA_ID is empty (the degenerate post-merge graph, as documented) while HEAD^1..HEAD^2 lists the real 4 files, including a docs/issues/ path"
  else
    pf_fail "TC-010 step 1: three-dot gave $n_threedot010 file(s) (want 0 — fixture did not reproduce the post-merge graph), HEAD^1..HEAD^2 gave $n_diff010 file(s) (want 4), docs/issues/ path present: $has_docs_issues010 (want 1) — diff: $diff010"
  fi

  filtered010="$(printf '%s\n' "$diff010" | pf_ptp_area_exclude_docs_issues)"
  n_filtered010="$(printf '%s\n' "$filtered010" | grep -c . || true)"
  if [ "$n_filtered010" -eq 3 ]; then
    pf_pass "TC-010 step 2: excluding docs/issues/ leaves 3 files"
  else
    pf_fail "TC-010 step 2: excluding docs/issues/ left $n_filtered010 file(s) (want 3) — filtered: $filtered010"
  fi

  winner010="$(printf '%s\n' "$filtered010" | pf_ptp_area_winner)"
  if [ "$winner010" = "pf-close" ]; then
    pf_pass "TC-010 step 3: pf-close (2 files, second segment of skills/pf-close/…) beats scripts (1 file, first segment)"
  else
    pf_fail "TC-010 step 3: Area winner was '$winner010' (want pf-close)"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_area_cmd=0
  has_area_exclude=0
  has_area_segment=0
  has_area_majority=0
  has_area_general=0
  printf '%s\n' "$sec45" | grep -qF 'HEAD^1 HEAD^2' && has_area_cmd=1
  printf '%s\n' "$sec45" | grep -qiE 'Exclude any paths under.{0,20}docs/issues/' && has_area_exclude=1
  printf '%s\n' "$sec45" | grep -qiE 'second path segment.{0,80}skills.{0,40}tools' && has_area_segment=1
  printf '%s\n' "$sec45" | grep -qiE 'segment with the most files wins' && has_area_majority=1
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF '`general`' && has_area_general=1
  if [ "$has_area_cmd" -eq 1 ] && [ "$has_area_exclude" -eq 1 ] && [ "$has_area_segment" -eq 1 ] &&
    [ "$has_area_majority" -eq 1 ] && [ "$has_area_general" -eq 1 ]; then
    pf_pass "TC-010 step 4: Phase 4.5 documents the HEAD^1 HEAD^2 diff, the docs/issues/ exclusion, segmentation and majority-wins"
  else
    pf_fail "TC-010 step 4: Phase 4.5 не документирует правило вычисления Area (cmd=$has_area_cmd exclude=$has_area_exclude segment=$has_area_segment majority=$has_area_majority general=$has_area_general)"
  fi
fi

# ─── Helpers: idempotency by (ISSUE-ID, TC-NNN), never the title (TC-015) ──

# pf_ptp_origin_exists <global test-plan.md file> <origin> — true (rc 0) iff a
# row with this exact Origin already exists in the table.
pf_ptp_origin_exists() {
  local file="$1" origin="$2"
  pf_ptp_parse_global_rows "$file" | awk -F'\037' -v o="$origin" '$5 == o { found = 1 } END { exit !found }'
}

# pf_ptp_promote_issue <issue test_plan.md> <ISSUE-ID> <global file>
# <closing date> [<area>] — Phase 4.5 steps 1+3+4 end to end for every Manual
# row of one issue. Idempotent: a row whose Origin (ISSUE-ID#TC-NNN) is
# already in the target is skipped outright — the identity key is the pair
# (ISSUE-ID, TC-NNN), never the case title (specs.md "Идемпотентность"),
# which is exactly what TC-015 exercises.
pf_ptp_promote_issue() {
  local issue_file="$1" issue_id="$2" target="$3" closing_date="$4" area="${5:-general}"
  local tc tcase type prio status origin prio_out prio_norm status_mapped lastrun
  # shellcheck disable=SC2034  # type must still be consumed for field alignment; rows are already Manual-only (pf_ptp_select_manual)
  while IFS=$'\037' read -r tc tcase type prio status; do
    [ -z "$tc" ] && continue
    origin="${issue_id}#${tc}"
    if pf_ptp_origin_exists "$target" "$origin"; then
      continue
    fi
    prio_out="$(pf_ptp_normalize_priority "$prio")"
    prio_norm="${prio_out%%$'\037'*}"
    status_mapped="$(pf_ptp_map_status "$status")"
    lastrun="$(pf_ptp_last_run "$status_mapped" "$closing_date")"
    pf_ptp_promote_row "$target" "$area" "$tcase" "$prio_norm" "$origin" "$lastrun" "$status_mapped" >/dev/null
  done < <(pf_ptp_select_manual "$issue_file")
}

TP_DUP="$REPO_ROOT/test/fixtures/pf-product-test-plan/issue-duplicate-titles/docs/issues/open/20990101-feat-fixture-duplicate-titles/test_plan.md"
DUP_ID="20990101-feat-fixture-duplicate-titles"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-015: idempotent re-run keyed on (ISSUE-ID, TC-NNN), not the title\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_DUP" ]; then
  pf_fail "TC-015: fixture test_plan.md not found: $TP_DUP"
else
  target015="$(pf_ptp_case_file "$PTP_FIX_FRESH")"
  if [ ! -f "$target015" ]; then
    pf_fail "TC-015: fixture docs/planning/test-plan.md not found ($PTP_FIX_FRESH)"
  else
    pf_ptp_promote_issue "$TP_DUP" "$DUP_ID" "$target015" "2026-08-11" "explorer-ui"

    n_rows015a="$(pf_ptp_parse_global_rows "$target015" | grep -c . || true)"
    has_tc001_origin=0
    has_tc002_origin=0
    grep -qF "${DUP_ID}#TC-001" "$target015" && has_tc001_origin=1
    grep -qF "${DUP_ID}#TC-002" "$target015" && has_tc002_origin=1
    ptc_tc001="$(pf_ptp_parse_global_rows "$target015" | awk -F'\037' -v o="${DUP_ID}#TC-001" '$5 == o { print $1 }')"
    ptc_tc002="$(pf_ptp_parse_global_rows "$target015" | awk -F'\037' -v o="${DUP_ID}#TC-002" '$5 == o { print $1 }')"

    if [ "$n_rows015a" -eq 2 ] && [ "$has_tc001_origin" -eq 1 ] && [ "$has_tc002_origin" -eq 1 ] &&
      [ -n "$ptc_tc001" ] && [ -n "$ptc_tc002" ] && [ "$ptc_tc001" != "$ptc_tc002" ]; then
      pf_pass "TC-015 step 1: two identically-titled Manual cases got distinct PTC numbers ($ptc_tc001 / $ptc_tc002) and distinct Origins"
    else
      pf_fail "TC-015 step 1: row_count=$n_rows015a tc001_origin=$has_tc001_origin tc002_origin=$has_tc002_origin ptc001=$ptc_tc001 ptc002=$ptc_tc002 (want 2 rows, both origins present, distinct PTCs)"
    fi

    last_alloc_before015="$(pf_ptp_counter_value "$target015")"
    pf_ptp_promote_issue "$TP_DUP" "$DUP_ID" "$target015" "2026-08-11" "explorer-ui"
    n_rows015b="$(pf_ptp_parse_global_rows "$target015" | grep -c . || true)"
    last_alloc_after015="$(pf_ptp_counter_value "$target015")"

    if [ "$n_rows015b" -eq 2 ] && [ "$last_alloc_after015" -eq "$last_alloc_before015" ]; then
      pf_pass "TC-015 step 2: re-running the promotion with no issue changes creates no new rows, Last allocated: unchanged"
    else
      pf_fail "TC-015 step 2: re-run row_count=$n_rows015b (want 2), Last allocated: $last_alloc_before015 -> $last_alloc_after015 (want unchanged)"
    fi
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_idem_pair=0
  has_idem_not_title=0
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  printf '%s\n' "$sec45" | grep -qF 'pair (`ISSUE-ID`, `TC-NNN`)' && has_idem_pair=1
  printf '%s\n' "$sec45" | grep -qiE 'never the case title' && has_idem_not_title=1
  if [ "$has_idem_pair" -eq 1 ] && [ "$has_idem_not_title" -eq 1 ]; then
    pf_pass "TC-015 step 3: Phase 4.5 documents the idempotency key as (ISSUE-ID, TC-NNN), never the title"
  else
    pf_fail "TC-015 step 3: Phase 4.5 не документирует ключ идемпотентности (ISSUE-ID, TC-NNN) (pair found: $has_idem_pair, not-title found: $has_idem_not_title)"
  fi
fi

# ─── Helpers: title self-containedness (TC-017) ────────────────────────────

# pf_ptp_read_description <issue test_plan.md> <TC-NNN> — the text after
# "**Description:**" for the "### TC-NNN: ..." section of that case. Empty if
# not found.
pf_ptp_read_description() {
  local file="$1" tc="$2"
  awk -v tc="$tc" '
    $0 ~ ("^### " tc ":") { intc = 1; next }
    intc && /^### / { exit }
    intc && /^\*\*Description:\*\*/ {
      sub(/^\*\*Description:\*\* */, "")
      print
      exit
    }
  ' "$file"
}

# pf_ptp_is_self_contained_title <title> — a title that names a bare step
# number ("Проверить шаг 3" / "Verify step 3") only reads in the context of
# the issue; anything else is treated as already self-contained. Transcribed
# heuristic for this fixture's two cases, not a general NLP rule.
pf_ptp_is_self_contained_title() {
  local title="$1"
  if [[ "$title" =~ ([Шш]аг|[Ss]tep)[[:space:]]+[0-9]+ ]]; then
    return 1
  fi
  return 0
}

# pf_ptp_expand_title <issue test_plan.md> <TC-NNN> <raw title> — Phase 4.5
# "Self-containedness": a context-dependent title is expanded using the
# issue's own Description field for that case; a title that already stands
# alone is returned verbatim.
pf_ptp_expand_title() {
  local file="$1" tc="$2" title="$3" desc
  if pf_ptp_is_self_contained_title "$title"; then
    printf '%s' "$title"
    return 0
  fi
  desc="$(pf_ptp_read_description "$file" "$tc")"
  if [ -n "$desc" ]; then
    printf '%s — %s' "$title" "$desc"
  else
    printf '%s' "$title"
  fi
}

TP_TITLE="$REPO_ROOT/test/fixtures/pf-product-test-plan/issue-non-self-contained-title/docs/issues/open/20990101-feat-fixture-title/test_plan.md"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-017: non-self-contained titles are expanded, self-contained ones transferred verbatim\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$TP_TITLE" ]; then
  pf_fail "TC-017: fixture test_plan.md not found: $TP_TITLE"
else
  title001="$(pf_ptp_field_for_tc "$TP_TITLE" "TC-001" 2)"
  title002="$(pf_ptp_field_for_tc "$TP_TITLE" "TC-002" 2)"

  expanded001="$(pf_ptp_expand_title "$TP_TITLE" "TC-001" "$title001")"
  if [ "$expanded001" = "$title001" ]; then
    pf_pass "TC-017 step 1: self-contained title '$title001' transferred verbatim"
  else
    pf_fail "TC-017 step 1: self-contained title changed ('$title001' -> '$expanded001')"
  fi

  expanded002="$(pf_ptp_expand_title "$TP_TITLE" "TC-002" "$title002")"
  if [ "${#expanded002}" -gt "${#title002}" ] && [ "$expanded002" != "$title002" ]; then
    pf_pass "TC-017 step 2: context-dependent title '$title002' expanded to a longer, non-bare phrase ('$expanded002')"
  else
    pf_fail "TC-017 step 2: '$title002' did not expand (got '$expanded002')"
  fi

  # Derived from the fixture's own Description, not a hardcoded word: the
  # expansion is only "readable without opening Origin" if the actual context
  # text made it into the transferred title, whatever that text happens to
  # say. A hardcoded keyword would silently stop discriminating the moment
  # the fixture's wording changed.
  desc002="$(pf_ptp_read_description "$TP_TITLE" "TC-002")"
  if [ -n "$desc002" ] && printf '%s' "$expanded002" | grep -qF "$desc002"; then
    pf_pass "TC-017 step 3: expanded title carries the issue's own Description text, readable without opening Origin"
  else
    pf_fail "TC-017 step 3: expanded title '$expanded002' does not contain the fixture's Description ('$desc002')"
  fi

  sec45="$(pf_ptp_phase45_section)"
  has_selfcontained_label=0
  has_expand_rule=0
  printf '%s\n' "$sec45" | grep -qF 'Self-containedness' && has_selfcontained_label=1
  printf '%s\n' "$sec45" | grep -qiE 'expand it into a self-contained phrase' && has_expand_rule=1
  if [ "$has_selfcontained_label" -eq 1 ] && [ "$has_expand_rule" -eq 1 ]; then
    pf_pass "TC-017 step 4: Phase 4.5 documents expanding non-self-contained titles into a self-contained phrase"
  else
    pf_fail "TC-017 step 4: Phase 4.5 не документирует правило самодостаточности Test case (AC-1.2) (label found: $has_selfcontained_label, rule found: $has_expand_rule)"
  fi
fi

# ─── Helpers: converge behavior for docs/planning/test-plan.md (TC-011,
# TC-012) ────────────────────────────────────────────────────────────────────

GLOBAL_TEST_PLAN_TEMPLATE="$REPO_ROOT/docs/planning/templates/global/test-plan.md"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-011: converge создаёт docs/planning/test-plan.md из шаблона, если файла нет\n'
# ══════════════════════════════════════════════════════════════════════════════

if [ ! -f "$GLOBAL_TEST_PLAN_TEMPLATE" ]; then
  pf_fail "TC-011 step 1: шаблон global/test-plan.md ещё не создан (задача реализации)"
else
  pf_pass "TC-011 step 1: docs/planning/templates/global/test-plan.md существует"

  pf_setup_case v3-incomplete >/dev/null
  rc011=0
  # shellcheck disable=SC2119  # pf_run_converge's args are optional; a deliberate zero-arg call (uses its default --target $TMP_WORK), same pattern as test/converge-migrate.sh
  pf_run_converge >/dev/null 2>&1 || rc011=$?
  target011="$TMP_WORK/docs/planning/test-plan.md"

  if [ "$rc011" -eq 0 ] && [ -f "$target011" ] && cmp -s "$GLOBAL_TEST_PLAN_TEMPLATE" "$target011"; then
    pf_pass "TC-011 step 2: pf_run_converge создаёт docs/planning/test-plan.md, побайтово совпадающий с шаблоном (exit $rc011)"
  elif [ ! -f "$target011" ]; then
    pf_fail "TC-011 step 2: t5_global_docs() не создаёт test-plan.md (файл отсутствует после pf_run_converge, exit $rc011)"
  else
    pf_fail "TC-011 step 2: t5_global_docs() не создаёт test-plan.md (файл создан, но отличается от шаблона побайтово, exit $rc011)"
    diff "$GLOBAL_TEST_PLAN_TEMPLATE" "$target011" >&2 || true
  fi
fi

# Precedent: test/safety-audit.sh assembles the convergence script's file name
# from adjacent string literals ("converge""-to-v3") so the auditor itself
# never becomes the extra file under test/ that names the script (rule S-1,
# test/lib.sh header). TC-012 step 1 needs to READ that script's source (to
# inspect t5_global_docs()'s file list) — the SAME trick is required here:
# spelling the name/path out as one literal would make this file the second
# place under test/ naming the script, and test/safety-audit.sh (TC-032, step
# 1) would go red. Do not "clean this up" into a plain literal.
PTP_CONVERGE_SCRIPT_NAME="converge""-to-v3"
PTP_CONVERGE_SCRIPT_PATH="$REPO_ROOT/scripts/${PTP_CONVERGE_SCRIPT_NAME}.sh"

# pf_ptp_t5_global_docs_body — the literal source of t5_global_docs() in the
# convergence script, from its opening line to its closing brace. A line-range
# extraction, not a whole-file grep: a mention of test-plan.md elsewhere in the
# script must not be able to satisfy TC-012 step 1 (implementation_plan.md
# Task 6).
pf_ptp_t5_global_docs_body() {
  awk '/^t5_global_docs\(\) \{/,/^}/' "$PTP_CONVERGE_SCRIPT_PATH"
}

VTP_EXISTING="$REPO_ROOT/test/fixtures/pf-product-test-plan/v3-with-existing-test-plan/docs/planning/test-plan.md"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-012: converge никогда не перезаписывает существующий docs/planning/test-plan.md\n'
# ══════════════════════════════════════════════════════════════════════════════

t5_body012="$(pf_ptp_t5_global_docs_body)"
if ! printf '%s\n' "$t5_body012" | grep -qF 'test-plan.md'; then
  pf_fail "TC-012 step 1: t5_global_docs() ещё не знает про test-plan.md"
else
  pf_pass "TC-012 step 1: t5_global_docs() перечисляет test-plan.md в переносимом списке файлов"

  if [ ! -f "$VTP_EXISTING" ]; then
    pf_fail "TC-012: fixture docs/planning/test-plan.md not found (v3-with-existing-test-plan)"
  else
    pf_setup_case v3-incomplete >/dev/null
    mkdir -p "$TMP_WORK/docs/planning"
    cp "$VTP_EXISTING" "$TMP_WORK/docs/planning/test-plan.md"

    snapshot_dir012="$(pf_mktemp_d)" || exit 1
    # Checked non-empty (and a real dir) before any use, same shape as
    # pf_ptp_area_setup's call site: an unguarded empty path here would let a
    # later `cp` write to bare "/before.md" instead of a throwaway temp dir —
    # the exact leak class this suite must never reproduce (S-4/S-5).
    if [ -z "$snapshot_dir012" ] || [ ! -d "$snapshot_dir012" ]; then
      pf_fail "TC-012: pf_mktemp_d did not return a usable temp dir for the before/after snapshot"
    else
      cp "$TMP_WORK/docs/planning/test-plan.md" "$snapshot_dir012/before.md"

      rc012=0
      # shellcheck disable=SC2119  # pf_run_converge's args are optional; a deliberate zero-arg call (uses its default --target $TMP_WORK), same pattern as test/converge-migrate.sh
      pf_run_converge >/dev/null 2>&1 || rc012=$?

      if [ "$rc012" -eq 0 ]; then
        pf_pass "TC-012 step 2: pf_run_converge завершается успешно на фикстуре с нешаблонным test-plan.md (exit $rc012)"
      else
        pf_fail "TC-012 step 2: pf_run_converge завершился с ошибкой на фикстуре с нешаблонным test-plan.md (exit $rc012)"
      fi

      if cmp -s "$snapshot_dir012/before.md" "$TMP_WORK/docs/planning/test-plan.md"; then
        pf_pass "TC-012 step 3: docs/planning/test-plan.md побайтово не изменился после pf_run_converge"
      else
        pf_fail "TC-012 step 3: t5_global_docs() перезаписывает пользовательский test-plan.md"
        diff "$snapshot_dir012/before.md" "$TMP_WORK/docs/planning/test-plan.md" >&2 || true
      fi
    fi
  fi
fi

# ─── Helpers: TC-018/TC-019 (Task 7) — both reuse pf_validate_test_plan_file
# (Task 4) and pf_ptp_promote_row (Task 3); no new helpers of their own. ──────

GLOBAL_MANUAL_EDIT_FIX="global-manual-edit"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-018: a hand edit to Status survives a later promotion (AC-3.1)\n'
# ══════════════════════════════════════════════════════════════════════════════

if ! declare -F pf_validate_test_plan_file >/dev/null 2>&1; then
  pf_fail "TC-018 step 1: pf_validate_test_plan_file ещё не реализована (Task 4 не выполнена)"
else
  pf_pass "TC-018 step 1: pf_validate_test_plan_file реализована"

  tp018="$(pf_ptp_case_file "$GLOBAL_MANUAL_EDIT_FIX")"
  if [ -z "$tp018" ] || [ ! -f "$tp018" ]; then
    pf_fail "TC-018: fixture docs/planning/test-plan.md not found ($GLOBAL_MANUAL_EDIT_FIX)"
  else
    # Step 2: emulate a human hand-editing the row: Status pending -> ✓, and
    # filling in Last run. A literal substring replace (bash's single-slash
    # ${var/search/replace}, not sed) so no regex metacharacter in the row text
    # (there is none here, but the intent is to never rely on that) can bite.
    row018_pending="| PTC-0001 | explorer-ui | Тема сохраняется между перезагрузками страницы | High | 20260729-improve-manual-test-data#TC-020 | — | pending |"
    row018_edited="| PTC-0001 | explorer-ui | Тема сохраняется между перезагрузками страницы | High | 20260729-improve-manual-test-data#TC-020 | 2026-08-11 | ✓ |"

    content018="$(cat "$tp018")"
    if [[ "$content018" != *"$row018_pending"* ]]; then
      pf_fail "TC-018: global-manual-edit fixture's data row does not match the expected literal text (fixture drifted)"
    else
      content018="${content018/$row018_pending/$row018_edited}"
      printf '%s\n' "$content018" >"$tp018"

      handedited_row018_before="$(grep -E '^\| *PTC-0001 *\|' "$tp018" | head -1)"
      n_pipes018="$(printf '%s' "$handedited_row018_before" | grep -o -F '|' | grep -c . || true)"

      if [ "$handedited_row018_before" = "$row018_edited" ] && [ "$n_pipes018" -eq 8 ]; then
        pf_pass "TC-018 step 2: hand edit applied — Status: pending -> ✓, Last run filled in, row still an 8-pipe/7-field markdown table row"
      else
        pf_fail "TC-018 step 2: hand edit did not land as expected (row: '$handedited_row018_before', pipe count: $n_pipes018, want 8)"
      fi

      out018="$(pf_validate_test_plan_file "$tp018" 2>&1)"
      rc018=$?
      if [ "$rc018" -eq 0 ]; then
        pf_pass "TC-018 step 3: pf_validate_test_plan_file accepts the hand-edited ✓ status"
      else
        pf_fail "TC-018 step 3: pf_validate_test_plan_file rejected the hand-edited row: $out018"
      fi

      # Step 4: promote one new Manual case (same pf_ptp_promote_row helper
      # TC-004..006/009 use) onto the same file, and prove the hand-edited row
      # is untouched — not just "still parses", but byte-identical to what the
      # human left after step 2.
      pf_ptp_promote_row "$tp018" "explorer-ui" \
        "Ещё один новый Manual-кейс поверх ручной правки" "High" \
        "20990101-feat-fixture-manualedit#TC-002" "—" "pending" >/dev/null

      handedited_row018_after="$(grep -E '^\| *PTC-0001 *\|' "$tp018" | head -1)"

      if [ "$handedited_row018_after" = "$handedited_row018_before" ]; then
        pf_pass "TC-018 step 4: hand-edited row (PTC-0001) is byte-identical after promoting a new Manual case"
      else
        pf_fail "TC-018 step 4: promotion altered the hand-edited row — before: '$handedited_row018_before' after: '$handedited_row018_after'"
      fi
    fi
  fi
fi

# ─── Helper: TC-019 fixture name ────────────────────────────────────────────

GLOBAL_RETIRED_FIX="global-retired-row"

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-019: a retired row is neither deleted nor its number reused (AC-3.3)\n'
# ══════════════════════════════════════════════════════════════════════════════

if ! declare -F pf_validate_test_plan_file >/dev/null 2>&1; then
  pf_fail "TC-019 step 1: pf_validate_test_plan_file ещё не реализована (Task 4 не выполнена)"
else
  pf_pass "TC-019 step 1: pf_validate_test_plan_file реализована"

  tp019="$(pf_ptp_case_file "$GLOBAL_RETIRED_FIX")"
  if [ -z "$tp019" ] || [ ! -f "$tp019" ]; then
    pf_fail "TC-019: fixture docs/planning/test-plan.md not found ($GLOBAL_RETIRED_FIX)"
  else
    snapshot019_dir="$(pf_mktemp_d)" || exit 1
    # Checked non-empty (and a real dir) before any use — same shape as
    # pf_ptp_area_setup's call site and TC-012's snapshot_dir012: an unguarded
    # empty path here would let the cp below write outside any throwaway temp
    # dir (S-4/S-5).
    if [ -z "$snapshot019_dir" ] || [ ! -d "$snapshot019_dir" ]; then
      pf_fail "TC-019: pf_mktemp_d did not return a usable temp dir for the before/after snapshot"
    else
      cp "$tp019" "$snapshot019_dir/before.md"

      out019="$(pf_validate_test_plan_file "$tp019" 2>&1)"
      rc019=$?
      if [ "$rc019" -eq 0 ]; then
        pf_pass "TC-019 step 2: pf_validate_test_plan_file accepts 'retired' as a valid Status dictionary value"
      else
        pf_fail "TC-019 step 2: pf_validate_test_plan_file rejected the retired row: $out019"
      fi

      if cmp -s "$snapshot019_dir/before.md" "$tp019" && grep -qF 'PTC-0003' "$tp019"; then
        pf_pass "TC-019 step 3: the file is byte-identical after validation (read-only), PTC-0003 is still present"
      else
        pf_fail "TC-019 step 3: the validator mutated the file, or PTC-0003 disappeared"
        diff "$snapshot019_dir/before.md" "$tp019" >&2 || true
      fi

      assigned019="$(pf_ptp_promote_row "$tp019" "explorer-ui" \
        "Ещё один новый Manual-кейс поверх файла со снятой строкой" "Low" \
        "20990101-feat-fixture-retired#TC-001" "—" "pending")"
      n_ptc0003_after="$(grep -c -F 'PTC-0003' "$tp019" || true)"
      retired_row019="$(grep -E '^\| *PTC-0003 *\|' "$tp019" | head -1)"

      if [ "$assigned019" = "PTC-0006" ] && [ "$n_ptc0003_after" -eq 1 ] && printf '%s' "$retired_row019" | grep -qF 'retired'; then
        pf_pass "TC-019 step 4: new row got PTC-0006 (max(Last allocated: PTC-0005, table max PTC-0005) + 1); PTC-0003 appears exactly once, row still present and still retired"
      else
        pf_fail "TC-019 step 4: new row got '$assigned019' (want PTC-0006); PTC-0003 occurrences=$n_ptc0003_after (want 1); retired row: '$retired_row019'"
      fi
    fi
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-020: правки по code review — порядок создания файла, stop-and-surface, восстановление счётчика\n'
# ══════════════════════════════════════════════════════════════════════════════
# code_review.md findings covered here:
#   P0 (finding 1) — Phase 4.5 step 1 now creates docs/planning/test-plan.md
#     BEFORE step 2's "no Manual rows -> proceed to Phase 5" early exit, not
#     after it (the pre-fix order broke Phase 8's git add on Auto-only issues).
#   P1 (finding 3) — step 2's three "stop and surface, never drop silently"
#     guards (Type neither Manual nor Auto; no Status Tracker table at all;
#     empty Test Case cell) and step 4's "Last allocated: line missing ->
#     recreate it" rule plus its called-out silent-failure mode.
#
# Boundary, stated once for steps 1-2 together: Phase 4.5 is prose an LLM agent
# executes, not code this file can run. Step 1 below asserts the SKILL.md TEXT
# is ordered correctly (line numbers only — reading the phase, not running it).
# Step 2 below runs a REAL `git add` in a throwaway repo to prove what actually
# happens when that ordering is violated — the P0 hazard itself, fully
# executable because it is plain git behaviour, not phase prose. Neither step
# claims to execute Phase 4.5; step 1 checks the recipe's order, step 2 checks
# the consequence of getting that order wrong.

if [ ! -f "$PF_CLOSE_SKILL" ]; then
  pf_fail "TC-020 step 1: skills/pf-close/SKILL.md does not exist"
else
  # Both sentences existed before the fix too (the early-exit line and the
  # file-creation instruction were both already in the text) — the defect was
  # purely their ORDER, so a plain "grep and confirm both exist" would have
  # passed on the broken revision as well. Only a line-number comparison
  # catches it.
  # shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
  line_ensure020="$(grep -n -F 'Ensure `docs/planning/test-plan.md` exists' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
  line_earlyexit020="$(grep -n -F 'this phase has nothing more to do; proceed to Phase 5' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

  if [ -n "$line_ensure020" ] && [ -n "$line_earlyexit020" ] && [ "$line_ensure020" -lt "$line_earlyexit020" ]; then
    pf_pass "TC-020 step 1: 'Ensure docs/planning/test-plan.md exists' (line $line_ensure020) идёт раньше выхода 'no Manual rows -> proceed to Phase 5' (line $line_earlyexit020) — файл создаётся до раннего выхода из фазы"
  else
    pf_fail "TC-020 step 1: порядок нарушен или текст не найден — ensure=${line_ensure020:-<missing>} earlyexit=${line_earlyexit020:-<missing>} (нужно ensure < earlyexit)"
  fi
fi

# TC-020 step 2 — the hazard itself, reproduced for real: Phase 8's git add
# with docs/planning/test-plan.md absent, exactly as measured in
# code_review.md's P0 finding. A throwaway git repo under pf_mktemp_d, never
# $REPO_ROOT (S-5).
tc020_repo="$(pf_mktemp_d)"
if [ -z "$tc020_repo" ] || [ ! -d "$tc020_repo" ]; then
  # Checked non-empty before any use — same shape as pf_ptp_area_setup's call
  # site: an unguarded empty path here would let `git -C`/`mkdir` below
  # silently target the caller's cwd instead of a throwaway temp dir (S-5
  # KNOWN GAP note in test/lib.sh).
  pf_fail "TC-020 step 2: pf_mktemp_d did not return a usable temp dir — probe repo skipped"
else
  git -C "$tc020_repo" init -q
  mkdir -p "$tc020_repo/docs/issues/closed/some-past-issue" "$tc020_repo/docs/planning"
  printf '# probe archived issue file\n' >"$tc020_repo/docs/issues/closed/some-past-issue/probe.md"
  printf '# Session Log\n' >"$tc020_repo/docs/planning/session-log.md"
  # docs/planning/test-plan.md is deliberately ABSENT — the pre-fix state for
  # an Auto-only issue, where step 1 never ran because it used to sit after
  # the early exit.

  git -C "$tc020_repo" \
    -c user.name='PF Test' -c user.email='pf-test@example.invalid' \
    add docs/issues/ docs/planning/session-log.md docs/planning/test-plan.md 2>/dev/null
  rc_add020=$?
  staged020="$(git -C "$tc020_repo" diff --cached --name-only)"
  n_staged020="$(printf '%s\n' "$staged020" | grep -c . || true)"

  if [ "$rc_add020" -ne 0 ]; then
    pf_pass "TC-020 step 2a: git add docs/issues/ docs/planning/session-log.md docs/planning/test-plan.md с отсутствующим test-plan.md завершается ненулевым кодом ($rc_add020)"
  else
    pf_fail "TC-020 step 2a: git add неожиданно завершился успешно (exit 0) с несуществующим test-plan.md в pathspec"
  fi

  if [ "$n_staged020" -eq 0 ]; then
    pf_pass "TC-020 step 2b: индекс остаётся пустым — ни docs/issues/, ни session-log.md не застейджены, хотя оба существуют и валидны"
  else
    pf_fail "TC-020 step 2b: индекс не пуст ($n_staged020 файл(ов)) — одна несуществующая pathspec не должна позволять частичный git add: $staged020"
  fi
fi

# TC-020 steps 3-6 — the stop-and-surface drift-guards (code_review.md P1,
# finding 3). Each guard's text was grepped for and confirmed present in the
# live SKILL.md before being written here — a guard on absent text would be
# permanently red, the anti-pattern implementation_plan.md's own P1-D
# condemns.
sec45_020="$(pf_ptp_phase45_section)"

has_stop_instruction020=0
printf '%s\n' "$sec45_020" | grep -qF 'stop and report the problem to the user instead of proceeding to Phase 5' && has_stop_instruction020=1
if [ "$has_stop_instruction020" -eq 1 ]; then
  pf_pass "TC-020 step 3: Phase 4.5 требует останавливаться и сообщать пользователю о нераспознанном входе, а не молча пропускать Phase 5"
else
  pf_fail "TC-020 step 3: Phase 4.5 не документирует правило stop-and-surface"
fi

has_guard_bad_type020=0
printf '%s\n' "$sec45_020" | grep -qiE 'Type.{0,10}is neither.{0,10}Manual.{0,10}nor.{0,10}Auto' && has_guard_bad_type020=1
if [ "$has_guard_bad_type020" -eq 1 ]; then
  pf_pass "TC-020 step 4: Phase 4.5 документирует останов на Type, который не Manual и не Auto (опечатка регистра, decorated-значение)"
else
  pf_fail "TC-020 step 4: Phase 4.5 не документирует останов при Type, не равном ни Manual, ни Auto"
fi

has_guard_no_table020=0
printf '%s\n' "$sec45_020" | grep -qF 'no Status Tracker table found at all' && has_guard_no_table020=1
if [ "$has_guard_no_table020" -eq 1 ]; then
  pf_pass "TC-020 step 5: Phase 4.5 отдельно документирует случай 'таблица Status Tracker не найдена вовсе' — отличный от легитимного 'нет строк Manual'"
else
  pf_fail "TC-020 step 5: Phase 4.5 не документирует останов при полном отсутствии таблицы Status Tracker (как случай, отдельный от 'нет Manual-строк')"
fi

has_guard_empty_title020=0
# shellcheck disable=SC2016  # backticks are markdown in a grep pattern, not command substitution
printf '%s\n' "$sec45_020" | grep -qF 'row whose `Test Case` cell is empty' && has_guard_empty_title020=1
if [ "$has_guard_empty_title020" -eq 1 ]; then
  pf_pass "TC-020 step 6: Phase 4.5 документирует останов на выбранной Manual-строке с пустой ячейкой Test Case"
else
  pf_fail "TC-020 step 6: Phase 4.5 не документирует останов при пустой ячейке Test Case у выбранной Manual-строки"
fi

# TC-020 steps 7-8 — the "Last allocated:" recreation rule (code_review.md P1,
# finding 3, 4th bullet) and its called-out silent-failure mode.
has_recreate_counter020=0
printf '%s\n' "$sec45_020" | grep -qiE 'Last allocated.{0,10}line is missing entirely, recreate it' && has_recreate_counter020=1
if [ "$has_recreate_counter020" -eq 1 ]; then
  pf_pass "TC-020 step 7: Phase 4.5 документирует восстановление отсутствующей строки Last allocated: (а не останов и не тихий пропуск)"
else
  pf_fail "TC-020 step 7: Phase 4.5 не документирует восстановление строки Last allocated: при её отсутствии"
fi

has_silent_failure_note020=0
if printf '%s\n' "$sec45_020" | grep -qiE 'sed.{0,10}style in-place substitution' &&
  printf '%s\n' "$sec45_020" | grep -qiE 'exits? 0 and changes nothing'; then
  has_silent_failure_note020=1
fi
if [ "$has_silent_failure_note020" -eq 1 ]; then
  pf_pass "TC-020 step 8: Phase 4.5 явно называет тихий отказ (sed-подстановка без совпадения завершается кодом 0 и ничего не меняет) как режим, которого нужно избегать"
else
  pf_fail "TC-020 step 8: Phase 4.5 не называет явно тихий режим отказа (sed-подстановка exit 0, файл не изменён)"
fi

# ══════════════════════════════════════════════════════════════════════════════
printf '\n=== TC-021: восстановление Phase 4.5 — частичная запись выбрасывается, а не сохраняется\n'
# ══════════════════════════════════════════════════════════════════════════════
# code_review.md pass 2 findings covered here: the documented recovery from a
# crash inside Phase 4.5 is NOT executable in a common shape (issue branch cut
# before docs/planning/test-plan.md existed on PARENT-BRANCH) unless the
# partial write is discarded before switching branches, and even where the
# naive checkout WOULD succeed, keeping the partial write makes Phase 4's
# re-run a second real merge commit instead of a no-op, so Area is computed
# from a bookkeeping-only diff instead of the issue's real file set.
#
# Steps 1-5 reproduce both halves for real in one throwaway git repo built
# under pf_mktemp_d (never $REPO_ROOT — S-5), continuing the SAME repo from
# the failed naive attempt into the successful discard-first attempt, exactly
# as the two recipes in the issue's own worked example share one scenario.
# Steps 6-7 drift-guard the documented rule itself, following TC-020's
# precedent: each pattern below was grepped and confirmed present in the live
# SKILL.md before being written here (implementation_plan.md P1-D — a guard on
# absent text is permanently red, never write one).

tc021_repo="$(pf_mktemp_d)"
if [ -z "$tc021_repo" ] || [ ! -d "$tc021_repo" ]; then
  # Checked non-empty before any use — same shape as pf_ptp_area_setup's call
  # site: an unguarded empty path here would let every git -C command below
  # silently target the caller's cwd instead of a throwaway temp dir (S-5
  # KNOWN GAP note in test/lib.sh).
  pf_fail "TC-021 step 1: pf_mktemp_d did not return a usable temp dir — probe repo skipped"
  pf_fail "TC-021 step 2: skipped — repo setup failed"
  pf_fail "TC-021 step 3: skipped — repo setup failed"
  pf_fail "TC-021 step 4: skipped — repo setup failed"
  pf_fail "TC-021 step 5: skipped — repo setup failed"
else
  git -C "$tc021_repo" init -q -b develop
  git -C "$tc021_repo" config user.email 'pf-test@example.invalid'
  git -C "$tc021_repo" config user.name 'PF Test'

  printf '# README\n' >"$tc021_repo/README.md"
  mkdir -p "$tc021_repo/docs/planning"
  printf '# Session Log\n' >"$tc021_repo/docs/planning/session-log.md"
  git -C "$tc021_repo" add -A
  git -C "$tc021_repo" commit -q -m 'initial commit'

  # Issue branch cut BEFORE docs/planning/test-plan.md exists anywhere in the
  # repo — the common shape code_review.md's finding turns on.
  git -C "$tc021_repo" checkout -q -b issue/X
  mkdir -p "$tc021_repo/skills/pf-close"
  printf '# probe skill change\n' >"$tc021_repo/skills/pf-close/SKILL.md"
  git -C "$tc021_repo" add -A
  git -C "$tc021_repo" commit -q -m 'issue change under skills/pf-close/'

  # test-plan.md introduced only on the parent, after the issue branch forked.
  git -C "$tc021_repo" checkout -q develop
  {
    printf '# Manual Test Plan\n\n'
    printf 'Last allocated: none\n\n'
    printf '| PTC | Area | Test case | Prio | Origin | Last run | Status |\n'
    printf '| --- | --- | --- | --- | --- | --- | --- |\n'
  } >"$tc021_repo/docs/planning/test-plan.md"
  git -C "$tc021_repo" add -A
  git -C "$tc021_repo" commit -q -m 'add test-plan.md (parent only)'

  # Phase 4.
  git -C "$tc021_repo" merge -q --no-ff issue/X -m 'merge: close X'
  merge_sha1_021="$(git -C "$tc021_repo" rev-parse HEAD)"

  # Phase 4.5 writes, then "crashes": an uncommitted append to the file the
  # merge just carried onto develop.
  printf 'probe promoted row\n' >>"$tc021_repo/docs/planning/test-plan.md"

  # ── Probe 1: the naive recovery step ("just switch back") is not
  # executable — the branch predates the file, so switching would have to
  # delete a locally-modified file and git refuses. ──────────────────────
  out_naive021="$(git -C "$tc021_repo" checkout issue/X 2>&1)"
  rc_naive021=$?
  branch_after_naive021="$(git -C "$tc021_repo" branch --show-current)"

  if [ "$rc_naive021" -ne 0 ]; then
    pf_pass "TC-021 step 1: наивное восстановление (git checkout issue/X сразу после сбоя, без выбрасывания частичной записи) завершается ненулевым кодом ($rc_naive021) — issue-ветка создана до появления docs/planning/test-plan.md на родителе, переключение удалило бы локально изменённый файл"
  else
    pf_fail "TC-021 step 1: наивный git checkout issue/X неожиданно завершился успешно (exit 0) при незакоммиченной частичной записи (output: $out_naive021)"
  fi

  if [ "$branch_after_naive021" = "develop" ]; then
    pf_pass "TC-021 step 2: после сбойного checkout текущая ветка осталась develop — переключения не произошло"
  else
    pf_fail "TC-021 step 2: текущая ветка после сбойного checkout — '$branch_after_naive021' (ожидалось develop)"
  fi

  # ── Probe 2: same scenario, discard first — the whole recovery works,
  # including Area on the re-merge. ───────────────────────────────────────
  git -C "$tc021_repo" checkout -q -- docs/planning/test-plan.md
  out_switch021="$(git -C "$tc021_repo" checkout issue/X 2>&1)"
  rc_switch021=$?

  if [ "$rc_switch021" -eq 0 ]; then
    pf_pass "TC-021 step 3: после git checkout -- docs/planning/test-plan.md (выбрасывание частичной записи) git checkout issue/X завершается успешно (exit 0)"
  else
    pf_fail "TC-021 step 3: git checkout issue/X после выбрасывания частичной записи всё равно завершился с кодом $rc_switch021 (output: $out_switch021)"
  fi

  git -C "$tc021_repo" checkout -q develop
  git -C "$tc021_repo" merge -q --no-ff issue/X -m 'merge: close X'
  rc_remerge021=$?
  merge_sha2_021="$(git -C "$tc021_repo" rev-parse HEAD)"

  if [ "$rc_remerge021" -eq 0 ] && [ -n "$merge_sha1_021" ] && [ "$merge_sha2_021" = "$merge_sha1_021" ]; then
    pf_pass "TC-021 step 4: повторный git merge --no-ff после выбрасывания частичной записи — настоящий no-op: HEAD побайтово совпадает с первым merge-коммитом ($merge_sha1_021)"
  else
    pf_fail "TC-021 step 4: повторный merge не no-op (exit $rc_remerge021) — HEAD было $merge_sha1_021, стало $merge_sha2_021"
  fi

  diff021="$(git -C "$tc021_repo" diff --name-only 'HEAD^1' 'HEAD^2')"
  has_skills_path021=0
  printf '%s\n' "$diff021" | grep -qF 'skills/pf-close/' && has_skills_path021=1
  if [ "$has_skills_path021" -eq 1 ]; then
    pf_pass "TC-021 step 5: git diff --name-only HEAD^1 HEAD^2 после восстановления по-прежнему содержит путь issue-ветки skills/pf-close/SKILL.md, а не только docs/planning/test-plan.md — Area вычислится из реального диффа issue, не из бухгалтерии"
  else
    pf_fail "TC-021 step 5: git diff --name-only HEAD^1 HEAD^2 не содержит skills/pf-close/SKILL.md — Area посчитался бы по бухгалтерии, а не по реальному диффу issue (diff: $diff021)"
  fi
fi

# TC-021 steps 6-7 — drift-guards on the recovery rule itself (code_review.md
# pass 2). Each pattern was grepped against the live SKILL.md and confirmed
# present before being written here.
line_discard021="$(grep -nF 'Throw the partial write away' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"
# shellcheck disable=SC2016  # backtick+period is markdown in a grep pattern, not command substitution
line_switch021="$(grep -nF '`git checkout issue/ISSUE-ID`.' "$PF_CLOSE_SKILL" | head -1 | cut -d: -f1)"

if [ -n "$line_discard021" ] && [ -n "$line_switch021" ] && [ "$line_discard021" -lt "$line_switch021" ]; then
  pf_pass "TC-021 step 6: 'Throw the partial write away' (line $line_discard021) идёт раньше 'git checkout issue/ISSUE-ID' (line $line_switch021) — выбрасывание частичной записи предписано ДО переключения веток"
else
  pf_fail "TC-021 step 6: порядок инструкций восстановления нарушен или текст не найден — discard=${line_discard021:-<missing>} switch=${line_switch021:-<missing>} (нужно discard < switch)"
fi

sec45_021="$(pf_ptp_phase45_section)"
has_abort_consequence021=0
has_area_consequence021=0
printf '%s\n' "$sec45_021" | grep -qiE 'Step 2 aborts outright' && has_abort_consequence021=1
printf '%s\n' "$sec45_021" | grep -qiE 'second.{0,10}merge commit' && has_area_consequence021=1
if [ "$has_abort_consequence021" -eq 1 ] && [ "$has_area_consequence021" -eq 1 ]; then
  pf_pass "TC-021 step 7: Phase 4.5 явно называет оба следствия сохранения частичной записи — отказ checkout (Step 2 aborts outright) и неверный Area из-за второго merge-коммита"
else
  pf_fail "TC-021 step 7: Phase 4.5 не называет оба следствия сохранения частичной записи (abort found: $has_abort_consequence021, second-merge/Area found: $has_area_consequence021)"
fi

assert_repo_untouched
pf_summary
